/* gpx-parser-xml.c generated by valac 0.28.1, the Vala compiler
 * generated from gpx-parser-xml.vala, do not modify */

/* Gpx Viewer
 * Copyright (C) 2009-2015 Qball Cow <qball@sarine.nl>
 * Project homepage: http://blog.sarine.nl/

 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include <glib.h>
#include <glib-object.h>
#include "gpx.h"
#include <gio/gio.h>
#include <libxml/tree.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <libxml/xmlreader.h>
#include <libxml/xmlIO.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _gpx_point_unref0(var) ((var == NULL) ? NULL : (var = (gpx_point_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _xmlFreeTextReader0(var) ((var == NULL) ? NULL : (var = (xmlFreeTextReader (var), NULL)))

struct _GpxXmlFilePrivate {
	GFileInputStream* stream;
};


static gpointer gpx_xml_file_parent_class = NULL;

#define GPX_XML_FILE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GPX_TYPE_XML_FILE, GpxXmlFilePrivate))
enum  {
	GPX_XML_FILE_DUMMY_PROPERTY
};
static GpxTrack* gpx_xml_file_parse_track (GpxXmlFile* self, xmlNode* node);
static void gpx_xml_file_parse_waypoint (GpxXmlFile* self, xmlNode* node);
static GpxTrack* gpx_xml_file_parse_route (GpxXmlFile* self, xmlNode* node);
static gint gpx_xml_file_read_file (GpxXmlFile* self, guint8* buffer, int buffer_length1);
static gint gpx_xml_file_close_file (GpxXmlFile* self);
static void gpx_xml_file_finalize (GObject* obj);


static gdouble double_parse (const gchar* str) {
	gdouble result = 0.0;
	const gchar* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	g_return_val_if_fail (str != NULL, 0.0);
	_tmp0_ = str;
	_tmp1_ = g_ascii_strtod (_tmp0_, NULL);
	result = _tmp1_;
	return result;
}


static GpxTrack* gpx_xml_file_parse_track (GpxXmlFile* self, xmlNode* node) {
	GpxTrack* result = NULL;
	GpxTrack* track = NULL;
	GpxTrack* _tmp0_ = NULL;
	xmlNode* trkseg = NULL;
	xmlNode* _tmp1_ = NULL;
	xmlNode* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gpx_track_new ();
	track = _tmp0_;
	_tmp1_ = node;
	_tmp2_ = _tmp1_->children;
	trkseg = _tmp2_;
	while (TRUE) {
		xmlNode* _tmp3_ = NULL;
		xmlNode* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		xmlNode* _tmp75_ = NULL;
		const gchar* _tmp76_ = NULL;
		xmlNode* _tmp87_ = NULL;
		xmlNode* _tmp88_ = NULL;
		_tmp3_ = trkseg;
		if (!(_tmp3_ != NULL)) {
			break;
		}
		_tmp4_ = trkseg;
		_tmp5_ = _tmp4_->name;
		if (g_strcmp0 (_tmp5_, "trkseg") == 0) {
			xmlNode* point = NULL;
			xmlNode* _tmp6_ = NULL;
			xmlNode* _tmp7_ = NULL;
			_tmp6_ = trkseg;
			_tmp7_ = _tmp6_->children;
			point = _tmp7_;
			while (TRUE) {
				xmlNode* _tmp8_ = NULL;
				xmlNode* _tmp9_ = NULL;
				const gchar* _tmp10_ = NULL;
				xmlNode* _tmp73_ = NULL;
				xmlNode* _tmp74_ = NULL;
				_tmp8_ = point;
				if (!(_tmp8_ != NULL)) {
					break;
				}
				_tmp9_ = point;
				_tmp10_ = _tmp9_->name;
				if (g_strcmp0 (_tmp10_, "trkpt") == 0) {
					gchar* lat = NULL;
					xmlNode* _tmp11_ = NULL;
					gchar* _tmp12_ = NULL;
					gchar* lon = NULL;
					xmlNode* _tmp13_ = NULL;
					gchar* _tmp14_ = NULL;
					gboolean _tmp15_ = FALSE;
					const gchar* _tmp16_ = NULL;
					_tmp11_ = point;
					_tmp12_ = (gchar*) xmlGetProp (_tmp11_, (xmlChar*) "lat");
					lat = _tmp12_;
					_tmp13_ = point;
					_tmp14_ = (gchar*) xmlGetProp (_tmp13_, (xmlChar*) "lon");
					lon = _tmp14_;
					_tmp16_ = lat;
					if (_tmp16_ != NULL) {
						const gchar* _tmp17_ = NULL;
						_tmp17_ = lon;
						_tmp15_ = _tmp17_ != NULL;
					} else {
						_tmp15_ = FALSE;
					}
					if (_tmp15_) {
						GpxPoint* p = NULL;
						GpxPoint* _tmp18_ = NULL;
						gdouble flat = 0.0;
						const gchar* _tmp19_ = NULL;
						gdouble _tmp20_ = 0.0;
						gdouble flon = 0.0;
						const gchar* _tmp21_ = NULL;
						gdouble _tmp22_ = 0.0;
						GpxPoint* _tmp23_ = NULL;
						gdouble _tmp24_ = 0.0;
						gdouble _tmp25_ = 0.0;
						xmlNode* info = NULL;
						xmlNode* _tmp26_ = NULL;
						xmlNode* _tmp27_ = NULL;
						GpxPoint* _tmp67_ = NULL;
						const gchar* _tmp68_ = NULL;
						_tmp18_ = gpx_point_new ();
						p = _tmp18_;
						_tmp19_ = lat;
						_tmp20_ = double_parse (_tmp19_);
						flat = _tmp20_;
						_tmp21_ = lon;
						_tmp22_ = double_parse (_tmp21_);
						flon = _tmp22_;
						_tmp23_ = p;
						_tmp24_ = flat;
						_tmp25_ = flon;
						gpx_point_set_position (_tmp23_, _tmp24_, _tmp25_);
						_tmp26_ = point;
						_tmp27_ = _tmp26_->children;
						info = _tmp27_;
						while (TRUE) {
							xmlNode* _tmp28_ = NULL;
							xmlNode* _tmp29_ = NULL;
							const gchar* _tmp30_ = NULL;
							xmlNode* _tmp65_ = NULL;
							xmlNode* _tmp66_ = NULL;
							_tmp28_ = info;
							if (!(_tmp28_ != NULL)) {
								break;
							}
							_tmp29_ = info;
							_tmp30_ = _tmp29_->name;
							if (g_strcmp0 (_tmp30_, "ele") == 0) {
								gchar* content = NULL;
								xmlNode* _tmp31_ = NULL;
								gchar* _tmp32_ = NULL;
								const gchar* _tmp33_ = NULL;
								_tmp31_ = info;
								_tmp32_ = (gchar*) xmlNodeGetContent (_tmp31_);
								content = _tmp32_;
								_tmp33_ = content;
								if (_tmp33_ != NULL) {
									GpxPoint* _tmp34_ = NULL;
									const gchar* _tmp35_ = NULL;
									gdouble _tmp36_ = 0.0;
									_tmp34_ = p;
									_tmp35_ = content;
									_tmp36_ = double_parse (_tmp35_);
									_tmp34_->elevation = _tmp36_;
								}
								_g_free0 (content);
							} else {
								xmlNode* _tmp37_ = NULL;
								const gchar* _tmp38_ = NULL;
								_tmp37_ = info;
								_tmp38_ = _tmp37_->name;
								if (g_strcmp0 (_tmp38_, "time") == 0) {
									GpxPoint* _tmp39_ = NULL;
									xmlNode* _tmp40_ = NULL;
									gchar* _tmp41_ = NULL;
									_tmp39_ = p;
									_tmp40_ = info;
									_tmp41_ = (gchar*) xmlNodeGetContent (_tmp40_);
									_g_free0 (_tmp39_->time);
									_tmp39_->time = _tmp41_;
								} else {
									xmlNode* _tmp42_ = NULL;
									const gchar* _tmp43_ = NULL;
									_tmp42_ = info;
									_tmp43_ = _tmp42_->name;
									if (g_strcmp0 (_tmp43_, "extensions") == 0) {
										xmlNode* exts = NULL;
										xmlNode* _tmp44_ = NULL;
										xmlNode* _tmp45_ = NULL;
										_tmp44_ = info;
										_tmp45_ = _tmp44_->children;
										exts = _tmp45_;
										{
											gboolean _tmp46_ = FALSE;
											_tmp46_ = TRUE;
											while (TRUE) {
												xmlNode* _tmp49_ = NULL;
												xmlNode* _tmp50_ = NULL;
												const gchar* _tmp51_ = NULL;
												if (!_tmp46_) {
													xmlNode* _tmp47_ = NULL;
													xmlNode* _tmp48_ = NULL;
													_tmp47_ = exts;
													_tmp48_ = _tmp47_->next;
													exts = _tmp48_;
												}
												_tmp46_ = FALSE;
												_tmp49_ = exts;
												if (!(_tmp49_ != NULL)) {
													break;
												}
												_tmp50_ = exts;
												_tmp51_ = _tmp50_->name;
												if (g_strcmp0 (_tmp51_, "TrackPointExtension") == 0) {
													xmlNode* ext = NULL;
													xmlNode* _tmp52_ = NULL;
													xmlNode* _tmp53_ = NULL;
													_tmp52_ = exts;
													_tmp53_ = _tmp52_->children;
													ext = _tmp53_;
													{
														gboolean _tmp54_ = FALSE;
														_tmp54_ = TRUE;
														while (TRUE) {
															xmlNode* _tmp57_ = NULL;
															xmlNode* _tmp58_ = NULL;
															const gchar* _tmp59_ = NULL;
															if (!_tmp54_) {
																xmlNode* _tmp55_ = NULL;
																xmlNode* _tmp56_ = NULL;
																_tmp55_ = ext;
																_tmp56_ = _tmp55_->next;
																ext = _tmp56_;
															}
															_tmp54_ = FALSE;
															_tmp57_ = ext;
															if (!(_tmp57_ != NULL)) {
																break;
															}
															_tmp58_ = ext;
															_tmp59_ = _tmp58_->name;
															if (g_strcmp0 (_tmp59_, "hr") == 0) {
																gchar* val = NULL;
																xmlNode* _tmp60_ = NULL;
																gchar* _tmp61_ = NULL;
																GpxPoint* _tmp62_ = NULL;
																const gchar* _tmp63_ = NULL;
																gint _tmp64_ = 0;
																_tmp60_ = ext;
																_tmp61_ = (gchar*) xmlNodeGetContent (_tmp60_);
																val = _tmp61_;
																_tmp62_ = p;
																_tmp63_ = val;
																_tmp64_ = atoi (_tmp63_);
																_tmp62_->tpe.heartrate = _tmp64_;
																_g_free0 (val);
															}
														}
													}
												}
											}
										}
									}
								}
							}
							_tmp65_ = info;
							_tmp66_ = _tmp65_->next;
							info = _tmp66_;
						}
						_tmp67_ = p;
						_tmp68_ = _tmp67_->time;
						if (_tmp68_ != NULL) {
							GpxTrack* _tmp69_ = NULL;
							GpxPoint* _tmp70_ = NULL;
							_tmp69_ = track;
							_tmp70_ = p;
							gpx_track_add_point (_tmp69_, _tmp70_);
						}
						_gpx_point_unref0 (p);
					} else {
						xmlNode* _tmp71_ = NULL;
						const gchar* _tmp72_ = NULL;
						_tmp71_ = point;
						_tmp72_ = _tmp71_->name;
						g_message ("gpx-parser-xml.vala:94: Failed to get point: %s\n", _tmp72_);
					}
					_g_free0 (lon);
					_g_free0 (lat);
				}
				_tmp73_ = point;
				_tmp74_ = _tmp73_->next;
				point = _tmp74_;
			}
		}
		_tmp75_ = trkseg;
		_tmp76_ = _tmp75_->name;
		if (g_strcmp0 (_tmp76_, "name") == 0) {
			GpxTrack* _tmp77_ = NULL;
			const gchar* _tmp78_ = NULL;
			const gchar* _tmp79_ = NULL;
			_tmp77_ = track;
			_tmp78_ = gpx_track_get_name (_tmp77_);
			_tmp79_ = _tmp78_;
			if (_tmp79_ == NULL) {
				GpxTrack* _tmp80_ = NULL;
				xmlNode* _tmp81_ = NULL;
				gchar* _tmp82_ = NULL;
				gchar* _tmp83_ = NULL;
				_tmp80_ = track;
				_tmp81_ = trkseg;
				_tmp82_ = (gchar*) xmlNodeGetContent (_tmp81_);
				_tmp83_ = _tmp82_;
				gpx_track_set_name (_tmp80_, _tmp83_);
				_g_free0 (_tmp83_);
			} else {
				GpxTrack* _tmp84_ = NULL;
				const gchar* _tmp85_ = NULL;
				const gchar* _tmp86_ = NULL;
				_tmp84_ = track;
				_tmp85_ = gpx_track_get_name (_tmp84_);
				_tmp86_ = _tmp85_;
				g_warning ("gpx-parser-xml.vala:108: Track name allready set: %s\n", _tmp86_);
			}
		}
		_tmp87_ = trkseg;
		_tmp88_ = _tmp87_->next;
		trkseg = _tmp88_;
	}
	result = track;
	return result;
}


static gpointer _gpx_point_ref0 (gpointer self) {
	return self ? gpx_point_ref (self) : NULL;
}


static void gpx_xml_file_parse_waypoint (GpxXmlFile* self, xmlNode* node) {
	gchar* lat = NULL;
	xmlNode* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* lon = NULL;
	xmlNode* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	const gchar* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = node;
	_tmp1_ = (gchar*) xmlGetProp (_tmp0_, (xmlChar*) "lat");
	lat = _tmp1_;
	_tmp2_ = node;
	_tmp3_ = (gchar*) xmlGetProp (_tmp2_, (xmlChar*) "lon");
	lon = _tmp3_;
	_tmp5_ = lat;
	if (_tmp5_ != NULL) {
		const gchar* _tmp6_ = NULL;
		_tmp6_ = lon;
		_tmp4_ = _tmp6_ != NULL;
	} else {
		_tmp4_ = FALSE;
	}
	if (_tmp4_) {
		GpxPoint* p = NULL;
		GpxPoint* _tmp7_ = NULL;
		gdouble flat = 0.0;
		const gchar* _tmp8_ = NULL;
		gdouble _tmp9_ = 0.0;
		gdouble flon = 0.0;
		const gchar* _tmp10_ = NULL;
		gdouble _tmp11_ = 0.0;
		GpxPoint* _tmp12_ = NULL;
		gdouble _tmp13_ = 0.0;
		gdouble _tmp14_ = 0.0;
		xmlNode* info = NULL;
		xmlNode* _tmp15_ = NULL;
		xmlNode* _tmp16_ = NULL;
		GpxPoint* _tmp32_ = NULL;
		GpxPoint* _tmp33_ = NULL;
		_tmp7_ = gpx_point_new ();
		p = _tmp7_;
		_tmp8_ = lat;
		_tmp9_ = double_parse (_tmp8_);
		flat = _tmp9_;
		_tmp10_ = lon;
		_tmp11_ = double_parse (_tmp10_);
		flon = _tmp11_;
		_tmp12_ = p;
		_tmp13_ = flat;
		_tmp14_ = flon;
		gpx_point_set_position (_tmp12_, _tmp13_, _tmp14_);
		_tmp15_ = node;
		_tmp16_ = _tmp15_->children;
		info = _tmp16_;
		while (TRUE) {
			xmlNode* _tmp17_ = NULL;
			xmlNode* _tmp18_ = NULL;
			const gchar* _tmp19_ = NULL;
			xmlNode* _tmp30_ = NULL;
			xmlNode* _tmp31_ = NULL;
			_tmp17_ = info;
			if (!(_tmp17_ != NULL)) {
				break;
			}
			_tmp18_ = info;
			_tmp19_ = _tmp18_->name;
			if (g_strcmp0 (_tmp19_, "name") == 0) {
				GpxPoint* _tmp20_ = NULL;
				const gchar* _tmp21_ = NULL;
				const gchar* _tmp22_ = NULL;
				_tmp20_ = p;
				_tmp21_ = gpx_point_get_name (_tmp20_);
				_tmp22_ = _tmp21_;
				if (_tmp22_ == NULL) {
					GpxPoint* _tmp23_ = NULL;
					xmlNode* _tmp24_ = NULL;
					gchar* _tmp25_ = NULL;
					gchar* _tmp26_ = NULL;
					_tmp23_ = p;
					_tmp24_ = info;
					_tmp25_ = (gchar*) xmlNodeGetContent (_tmp24_);
					_tmp26_ = _tmp25_;
					gpx_point_set_name (_tmp23_, _tmp26_);
					_g_free0 (_tmp26_);
				} else {
					GpxPoint* _tmp27_ = NULL;
					const gchar* _tmp28_ = NULL;
					const gchar* _tmp29_ = NULL;
					_tmp27_ = p;
					_tmp28_ = gpx_point_get_name (_tmp27_);
					_tmp29_ = _tmp28_;
					g_warning ("gpx-parser-xml.vala:139: Point name allready set: %s\n", _tmp29_);
				}
			}
			_tmp30_ = info;
			_tmp31_ = _tmp30_->next;
			info = _tmp31_;
		}
		_tmp32_ = p;
		_tmp33_ = _gpx_point_ref0 (_tmp32_);
		((GpxFileBase*) self)->waypoints = g_list_append (((GpxFileBase*) self)->waypoints, _tmp33_);
		_gpx_point_unref0 (p);
	}
	_g_free0 (lon);
	_g_free0 (lat);
}


static GpxTrack* gpx_xml_file_parse_route (GpxXmlFile* self, xmlNode* node) {
	GpxTrack* result = NULL;
	GpxTrack* track = NULL;
	GpxTrack* _tmp0_ = NULL;
	xmlNode* trkseg = NULL;
	xmlNode* _tmp1_ = NULL;
	xmlNode* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gpx_track_new ();
	track = _tmp0_;
	_tmp1_ = node;
	_tmp2_ = _tmp1_->children;
	trkseg = _tmp2_;
	while (TRUE) {
		xmlNode* _tmp3_ = NULL;
		xmlNode* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		xmlNode* _tmp57_ = NULL;
		xmlNode* _tmp58_ = NULL;
		_tmp3_ = trkseg;
		if (!(_tmp3_ != NULL)) {
			break;
		}
		_tmp4_ = trkseg;
		_tmp5_ = _tmp4_->name;
		if (g_strcmp0 (_tmp5_, "rtept") == 0) {
			gchar* lat = NULL;
			xmlNode* _tmp6_ = NULL;
			gchar* _tmp7_ = NULL;
			gchar* lon = NULL;
			xmlNode* _tmp8_ = NULL;
			gchar* _tmp9_ = NULL;
			gboolean _tmp10_ = FALSE;
			const gchar* _tmp11_ = NULL;
			_tmp6_ = trkseg;
			_tmp7_ = (gchar*) xmlGetProp (_tmp6_, (xmlChar*) "lat");
			lat = _tmp7_;
			_tmp8_ = trkseg;
			_tmp9_ = (gchar*) xmlGetProp (_tmp8_, (xmlChar*) "lon");
			lon = _tmp9_;
			_tmp11_ = lat;
			if (_tmp11_ != NULL) {
				const gchar* _tmp12_ = NULL;
				_tmp12_ = lon;
				_tmp10_ = _tmp12_ != NULL;
			} else {
				_tmp10_ = FALSE;
			}
			if (_tmp10_) {
				GpxPoint* p = NULL;
				GpxPoint* _tmp13_ = NULL;
				gdouble flat = 0.0;
				const gchar* _tmp14_ = NULL;
				gdouble _tmp15_ = 0.0;
				gdouble flon = 0.0;
				const gchar* _tmp16_ = NULL;
				gdouble _tmp17_ = 0.0;
				GpxPoint* _tmp18_ = NULL;
				gdouble _tmp19_ = 0.0;
				gdouble _tmp20_ = 0.0;
				xmlNode* info = NULL;
				xmlNode* _tmp21_ = NULL;
				xmlNode* _tmp22_ = NULL;
				GpxPoint* _tmp39_ = NULL;
				const gchar* _tmp40_ = NULL;
				_tmp13_ = gpx_point_new ();
				p = _tmp13_;
				_tmp14_ = lat;
				_tmp15_ = double_parse (_tmp14_);
				flat = _tmp15_;
				_tmp16_ = lon;
				_tmp17_ = double_parse (_tmp16_);
				flon = _tmp17_;
				_tmp18_ = p;
				_tmp19_ = flat;
				_tmp20_ = flon;
				gpx_point_set_position (_tmp18_, _tmp19_, _tmp20_);
				_tmp21_ = trkseg;
				_tmp22_ = _tmp21_->children;
				info = _tmp22_;
				while (TRUE) {
					xmlNode* _tmp23_ = NULL;
					xmlNode* _tmp24_ = NULL;
					const gchar* _tmp25_ = NULL;
					xmlNode* _tmp37_ = NULL;
					xmlNode* _tmp38_ = NULL;
					_tmp23_ = info;
					if (!(_tmp23_ != NULL)) {
						break;
					}
					_tmp24_ = info;
					_tmp25_ = _tmp24_->name;
					if (g_strcmp0 (_tmp25_, "ele") == 0) {
						gchar* content = NULL;
						xmlNode* _tmp26_ = NULL;
						gchar* _tmp27_ = NULL;
						const gchar* _tmp28_ = NULL;
						_tmp26_ = info;
						_tmp27_ = (gchar*) xmlNodeGetContent (_tmp26_);
						content = _tmp27_;
						_tmp28_ = content;
						if (_tmp28_ != NULL) {
							GpxPoint* _tmp29_ = NULL;
							const gchar* _tmp30_ = NULL;
							gdouble _tmp31_ = 0.0;
							_tmp29_ = p;
							_tmp30_ = content;
							_tmp31_ = double_parse (_tmp30_);
							_tmp29_->elevation = _tmp31_;
						}
						_g_free0 (content);
					} else {
						xmlNode* _tmp32_ = NULL;
						const gchar* _tmp33_ = NULL;
						_tmp32_ = info;
						_tmp33_ = _tmp32_->name;
						if (g_strcmp0 (_tmp33_, "time") == 0) {
							GpxPoint* _tmp34_ = NULL;
							xmlNode* _tmp35_ = NULL;
							gchar* _tmp36_ = NULL;
							_tmp34_ = p;
							_tmp35_ = info;
							_tmp36_ = (gchar*) xmlNodeGetContent (_tmp35_);
							_g_free0 (_tmp34_->time);
							_tmp34_->time = _tmp36_;
						}
					}
					_tmp37_ = info;
					_tmp38_ = _tmp37_->next;
					info = _tmp38_;
				}
				_tmp39_ = p;
				_tmp40_ = _tmp39_->time;
				if (_tmp40_ != NULL) {
					GpxTrack* _tmp41_ = NULL;
					GpxPoint* _tmp42_ = NULL;
					_tmp41_ = track;
					_tmp42_ = p;
					gpx_track_add_point (_tmp41_, _tmp42_);
				}
				_gpx_point_unref0 (p);
			} else {
				xmlNode* _tmp43_ = NULL;
				const gchar* _tmp44_ = NULL;
				_tmp43_ = trkseg;
				_tmp44_ = _tmp43_->name;
				g_message ("gpx-parser-xml.vala:189: Failed to get trkseg: %s\n", _tmp44_);
			}
			_g_free0 (lon);
			_g_free0 (lat);
		} else {
			xmlNode* _tmp45_ = NULL;
			const gchar* _tmp46_ = NULL;
			_tmp45_ = trkseg;
			_tmp46_ = _tmp45_->name;
			if (g_strcmp0 (_tmp46_, "name") == 0) {
				GpxTrack* _tmp47_ = NULL;
				const gchar* _tmp48_ = NULL;
				const gchar* _tmp49_ = NULL;
				_tmp47_ = track;
				_tmp48_ = gpx_track_get_name (_tmp47_);
				_tmp49_ = _tmp48_;
				if (_tmp49_ == NULL) {
					GpxTrack* _tmp50_ = NULL;
					xmlNode* _tmp51_ = NULL;
					gchar* _tmp52_ = NULL;
					gchar* _tmp53_ = NULL;
					_tmp50_ = track;
					_tmp51_ = trkseg;
					_tmp52_ = (gchar*) xmlNodeGetContent (_tmp51_);
					_tmp53_ = _tmp52_;
					gpx_track_set_name (_tmp50_, _tmp53_);
					_g_free0 (_tmp53_);
				} else {
					GpxTrack* _tmp54_ = NULL;
					const gchar* _tmp55_ = NULL;
					const gchar* _tmp56_ = NULL;
					_tmp54_ = track;
					_tmp55_ = gpx_track_get_name (_tmp54_);
					_tmp56_ = _tmp55_;
					g_warning ("gpx-parser-xml.vala:200: Track name allready set: %s\n", _tmp56_);
				}
			}
		}
		_tmp57_ = trkseg;
		_tmp58_ = _tmp57_->next;
		trkseg = _tmp58_;
	}
	result = track;
	return result;
}


static gint gpx_xml_file_read_file (GpxXmlFile* self, guint8* buffer, int buffer_length1) {
	gint result = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	{
		gssize value = 0L;
		GFileInputStream* _tmp0_ = NULL;
		guint8* _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		gssize _tmp2_ = 0L;
		_tmp0_ = self->priv->stream;
		_tmp1_ = buffer;
		_tmp1__length1 = buffer_length1;
		_tmp2_ = g_input_stream_read ((GInputStream*) _tmp0_, _tmp1_, (gsize) _tmp1__length1, NULL, &_inner_error_);
		value = _tmp2_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch1_g_error;
		}
		result = (gint) value;
		return result;
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		GError* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		g_critical ("gpx-parser-xml.vala:223: error reading from stream: %s\n", _tmp4_);
		result = -1;
		_g_error_free0 (e);
		return result;
	}
	__finally1:
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return 0;
}


static gint gpx_xml_file_close_file (GpxXmlFile* self) {
	gint result = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_log ("GPX PARSER", G_LOG_LEVEL_DEBUG, "gpx-parser-xml.vala:229: Close_file()");
	_g_object_unref0 (self->priv->stream);
	self->priv->stream = NULL;
	result = 0;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GpxXmlFile* gpx_xml_file_construct (GType object_type, GFile* file) {
	GpxXmlFile * self = NULL;
	GFile* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (file != NULL, NULL);
	self = (GpxXmlFile*) gpx_file_base_construct (object_type);
	_tmp0_ = file;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (((GpxFileBase*) self)->file);
	((GpxFileBase*) self)->file = _tmp1_;
	{
		GFileInputStream* _tmp2_ = NULL;
		GFile* _tmp3_ = NULL;
		GFileInputStream* _tmp4_ = NULL;
		GFileInputStream* _tmp5_ = NULL;
		xmlTextReader* reader = NULL;
		GFile* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		xmlTextReader* _tmp9_ = NULL;
		xmlTextReader* _tmp10_ = NULL;
		xmlTextReader* _tmp11_ = NULL;
		xmlTextReader* _tmp48_ = NULL;
		_tmp3_ = file;
		_tmp4_ = g_file_read (_tmp3_, NULL, &_inner_error_);
		_tmp2_ = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch2_g_error;
		}
		_tmp5_ = _tmp2_;
		_tmp2_ = NULL;
		_g_object_unref0 (self->priv->stream);
		self->priv->stream = _tmp5_;
		_tmp6_ = ((GpxFileBase*) self)->file;
		_tmp7_ = g_file_get_uri (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = xmlReaderForIO ((xmlInputReadCallback) gpx_xml_file_read_file, (xmlInputCloseCallback) gpx_xml_file_close_file, self, _tmp8_, "", 0);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		reader = _tmp10_;
		_tmp11_ = reader;
		if (_tmp11_ != NULL) {
			gint doc = 0;
			xmlTextReader* _tmp12_ = NULL;
			gint _tmp13_ = 0;
			_tmp12_ = reader;
			_tmp13_ = xmlTextReaderRead (_tmp12_);
			doc = _tmp13_;
			while (TRUE) {
				gint _tmp14_ = 0;
				gchar* name = NULL;
				xmlTextReader* _tmp15_ = NULL;
				const gchar* _tmp16_ = NULL;
				gchar* _tmp17_ = NULL;
				const gchar* _tmp18_ = NULL;
				_tmp14_ = doc;
				if (!(_tmp14_ == 1)) {
					break;
				}
				_tmp15_ = reader;
				_tmp16_ = (const gchar*) xmlTextReaderConstName (_tmp15_);
				_tmp17_ = g_strdup (_tmp16_);
				name = _tmp17_;
				_tmp18_ = name;
				if (g_strcmp0 (_tmp18_, "gpx") == 0) {
					gint doc2 = 0;
					xmlTextReader* _tmp19_ = NULL;
					gint _tmp20_ = 0;
					_tmp19_ = reader;
					_tmp20_ = xmlTextReaderRead (_tmp19_);
					doc2 = _tmp20_;
					while (TRUE) {
						gint _tmp21_ = 0;
						gchar* name2 = NULL;
						xmlTextReader* _tmp22_ = NULL;
						const gchar* _tmp23_ = NULL;
						gchar* _tmp24_ = NULL;
						const gchar* _tmp25_ = NULL;
						xmlTextReader* _tmp44_ = NULL;
						gint _tmp45_ = 0;
						_tmp21_ = doc2;
						if (!(_tmp21_ == 1)) {
							break;
						}
						_tmp22_ = reader;
						_tmp23_ = (const gchar*) xmlTextReaderConstName (_tmp22_);
						_tmp24_ = g_strdup (_tmp23_);
						name2 = _tmp24_;
						_tmp25_ = name2;
						if (g_strcmp0 (_tmp25_, "trk") == 0) {
							xmlNode* node = NULL;
							xmlTextReader* _tmp26_ = NULL;
							xmlNode* _tmp27_ = NULL;
							GpxTrack* track = NULL;
							xmlNode* _tmp28_ = NULL;
							GpxTrack* _tmp29_ = NULL;
							GpxTrack* _tmp30_ = NULL;
							GpxTrack* _tmp31_ = NULL;
							GpxTrack* _tmp32_ = NULL;
							_tmp26_ = reader;
							_tmp27_ = xmlTextReaderExpand (_tmp26_);
							node = _tmp27_;
							_tmp28_ = node;
							_tmp29_ = gpx_xml_file_parse_track (self, _tmp28_);
							track = _tmp29_;
							_tmp30_ = track;
							gpx_track_filter_points (_tmp30_);
							_tmp31_ = track;
							_tmp32_ = _g_object_ref0 (_tmp31_);
							((GpxFileBase*) self)->tracks = g_list_append (((GpxFileBase*) self)->tracks, _tmp32_);
							_g_object_unref0 (track);
						} else {
							const gchar* _tmp33_ = NULL;
							_tmp33_ = name2;
							if (g_strcmp0 (_tmp33_, "wpt") == 0) {
								xmlNode* node = NULL;
								xmlTextReader* _tmp34_ = NULL;
								xmlNode* _tmp35_ = NULL;
								xmlNode* _tmp36_ = NULL;
								_tmp34_ = reader;
								_tmp35_ = xmlTextReaderExpand (_tmp34_);
								node = _tmp35_;
								_tmp36_ = node;
								gpx_xml_file_parse_waypoint (self, _tmp36_);
							} else {
								const gchar* _tmp37_ = NULL;
								_tmp37_ = name2;
								if (g_strcmp0 (_tmp37_, "rte") == 0) {
									xmlNode* node = NULL;
									xmlTextReader* _tmp38_ = NULL;
									xmlNode* _tmp39_ = NULL;
									GpxTrack* track = NULL;
									xmlNode* _tmp40_ = NULL;
									GpxTrack* _tmp41_ = NULL;
									GpxTrack* _tmp42_ = NULL;
									GpxTrack* _tmp43_ = NULL;
									_tmp38_ = reader;
									_tmp39_ = xmlTextReaderExpand (_tmp38_);
									node = _tmp39_;
									_tmp40_ = node;
									_tmp41_ = gpx_xml_file_parse_route (self, _tmp40_);
									track = _tmp41_;
									_tmp42_ = track;
									_tmp43_ = _g_object_ref0 (_tmp42_);
									((GpxFileBase*) self)->routes = g_list_append (((GpxFileBase*) self)->routes, _tmp43_);
									_g_object_unref0 (track);
								}
							}
						}
						_tmp44_ = reader;
						_tmp45_ = xmlTextReaderNext (_tmp44_);
						doc2 = _tmp45_;
						_g_free0 (name2);
					}
				} else {
					xmlTextReader* _tmp46_ = NULL;
					gint _tmp47_ = 0;
					_tmp46_ = reader;
					_tmp47_ = xmlTextReaderRead (_tmp46_);
					doc = _tmp47_;
				}
				_g_free0 (name);
			}
		} else {
			g_message ("gpx-parser-xml.vala:291: Failed to open file");
		}
		_tmp48_ = reader;
		xmlTextReaderClose (_tmp48_);
		_xmlFreeTextReader0 (reader);
		_g_object_unref0 (_tmp2_);
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		GFile* _tmp49_ = NULL;
		gchar* _tmp50_ = NULL;
		gchar* _tmp51_ = NULL;
		GError* _tmp52_ = NULL;
		const gchar* _tmp53_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp49_ = ((GpxFileBase*) self)->file;
		_tmp50_ = g_file_get_uri (_tmp49_);
		_tmp51_ = _tmp50_;
		_tmp52_ = e;
		_tmp53_ = _tmp52_->message;
		g_critical ("gpx-parser-xml.vala:297: failed to open file: '%s' error: %s", _tmp51_, _tmp53_);
		_g_free0 (_tmp51_);
		_g_error_free0 (e);
	}
	__finally2:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	return self;
}


GpxXmlFile* gpx_xml_file_new (GFile* file) {
	return gpx_xml_file_construct (GPX_TYPE_XML_FILE, file);
}


static void gpx_xml_file_class_init (GpxXmlFileClass * klass) {
	gpx_xml_file_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GpxXmlFilePrivate));
	G_OBJECT_CLASS (klass)->finalize = gpx_xml_file_finalize;
}


static void gpx_xml_file_instance_init (GpxXmlFile * self) {
	self->priv = GPX_XML_FILE_GET_PRIVATE (self);
	self->priv->stream = NULL;
}


static void gpx_xml_file_finalize (GObject* obj) {
	GpxXmlFile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GPX_TYPE_XML_FILE, GpxXmlFile);
	_g_object_unref0 (self->priv->stream);
	G_OBJECT_CLASS (gpx_xml_file_parent_class)->finalize (obj);
}


GType gpx_xml_file_get_type (void) {
	static volatile gsize gpx_xml_file_type_id__volatile = 0;
	if (g_once_init_enter (&gpx_xml_file_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GpxXmlFileClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gpx_xml_file_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GpxXmlFile), 0, (GInstanceInitFunc) gpx_xml_file_instance_init, NULL };
		GType gpx_xml_file_type_id;
		gpx_xml_file_type_id = g_type_register_static (GPX_TYPE_FILE_BASE, "GpxXmlFile", &g_define_type_info, 0);
		g_once_init_leave (&gpx_xml_file_type_id__volatile, gpx_xml_file_type_id);
	}
	return gpx_xml_file_type_id__volatile;
}



