/* gpx-graph2.c generated by valac 0.28.1, the Vala compiler
 * generated from gpx-graph2.vala, do not modify */

/* Gpx Viewer
 * Copyright (C) 2009-2015 Qball Cow <qball@sarine.nl>
 * Project homepage: http://blog.sarine.nl/

 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <config.h>
#include "gpx.h"
#include <pango/pango.h>
#include <cairo.h>
#include <float.h>
#include <math.h>
#include <gdk/gdk.h>
#include <gee.h>
#include <gtk/gtk.h>
#include <pango/pangocairo.h>
#include <glib/gi18n-lib.h>
#include <stdio.h>
#include <time.h>
#include <gobject/gvaluecollector.h>

#define __vala_PangoFontDescription_free0(var) ((var == NULL) ? NULL : (var = (_vala_PangoFontDescription_free (var), NULL)))
#define _cairo_surface_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_surface_destroy (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gpx_graph2_view_data_unref0(var) ((var == NULL) ? NULL : (var = (gpx_graph2_view_data_unref (var), NULL)))
#define _gpx_2d_point_free0(var) ((var == NULL) ? NULL : (var = (gpx_2d_point_free (var), NULL)))
#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))
typedef struct _GpxGraph2ViewParamSpecData GpxGraph2ViewParamSpecData;
#define _gpx_point_unref0(var) ((var == NULL) ? NULL : (var = (gpx_point_unref (var), NULL)))
typedef struct _GpxParamSpecGraph GpxParamSpecGraph;

struct _GpxGraph2ViewPrivate {
	PangoFontDescription* fd;
	cairo_surface_t* surf;
	gdouble OFFSET_LEFT;
	gdouble OFFSET_BOTTOM;
	gdouble OFFSET_TOP;
	gdouble OFFSET_RIGHT;
	gint highlight;
	GdkRGBA GRID_STRONG;
	GdkRGBA GRID_LIGHT;
	GdkRGBA BACKGROUND;
	GdkRGBA BACKDROP;
	GdkRGBA X_AXIS_COLOR;
	gint AXIS_MARGIN;
};

struct _GpxGraph2ViewParamSpecData {
	GParamSpec parent_instance;
};

struct _GpxGraphPrivate {
	gint _smooth_factor;
	gboolean _show_points;
	GpxGraph2View* view;
};

struct _GpxParamSpecGraph {
	GParamSpec parent_instance;
};


static gpointer gpx_graph2_view_parent_class = NULL;
static gpointer gpx_graph2_view_data_parent_class = NULL;
static gpointer gpx_graph_parent_class = NULL;

#define LOG_DOMAIN "GPX_GRAPH"
#define unique_graph VERSION
#define GPX_GRAPH2_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GPX_TYPE_GRAPH2_VIEW, GpxGraph2ViewPrivate))
enum  {
	GPX_GRAPH2_VIEW_DUMMY_PROPERTY
};
static void _vala_PangoFontDescription_free (PangoFontDescription* self);
static void gpx_graph2_view_size_allocate_cb (GpxGraph2View* self, GtkAllocation* alloc);
static void _gpx_graph2_view_size_allocate_cb_gtk_widget_size_allocate (GtkWidget* _sender, GtkAllocation* allocation, gpointer self);
static gboolean gpx_graph2_view_button_press_event_cb (GpxGraph2View* self, GdkEventButton* event);
static gboolean _gpx_graph2_view_button_press_event_cb_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean gpx_graph2_view_motion_notify_event_cb (GpxGraph2View* self, GdkEventMotion* event);
static gboolean _gpx_graph2_view_motion_notify_event_cb_gtk_widget_motion_notify_event (GtkWidget* _sender, GdkEventMotion* event, gpointer self);
static gboolean gpx_graph2_view_button_release_event_cb (GpxGraph2View* self, GdkEventButton* event);
static gboolean _gpx_graph2_view_button_release_event_cb_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean gpx_graph2_view_expose_cb (GpxGraph2View* self, cairo_t* ctx);
static gboolean _gpx_graph2_view_expose_cb_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self);
static gint* gpx_graph2_view_index_from_x (GpxGraph2View* self, gdouble x);
static gint* _int_dup (gint* self);
static void gpx_graph2_view_get_graph_sizes (GpxGraph2View* self, Gpxgraph_sizes_t* result);
static void gpx_graph2_view_update_surface (GpxGraph2View* self, GtkWidget* win);
static void gpx_graph2_view_draw_axis (GpxGraph2View* self, cairo_t* ctx, PangoLayout* layout, GtkAllocation* alloc);
static void gpx_graph2_view_draw_highlight (GpxGraph2View* self, cairo_t* ctx, PangoLayout* layout, GtkAllocation* alloc);
enum  {
	GPX_GRAPH2_VIEW_DATA_DUMMY_PROPERTY
};
static GdkRGBA* _gdk_rgba_dup (GdkRGBA* self);
static void gpx_graph2_view_data_find_min_max (GpxGraph2ViewData* self);
static gdouble gpx_graph2_view_data_round_to_multiple (GpxGraph2ViewData* self, gdouble num_to_round, gint multiple, gboolean negative);
static void gpx_graph2_view_data_finalize (GpxGraph2ViewData* obj);
static void gpx_graph2_view_finalize (GObject* obj);
#define GPX_GRAPH_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GPX_TYPE_GRAPH, GpxGraphPrivate))
enum  {
	GPX_GRAPH_DUMMY_PROPERTY
};
static void g_cclosure_user_marshal_VOID__OBJECT_GPX_POINT_GPX_POINT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void gpx_graph_finalize (GpxGraph* obj);


Gpx2DPoint* gpx_2d_point_dup (const Gpx2DPoint* self) {
	Gpx2DPoint* dup;
	dup = g_new0 (Gpx2DPoint, 1);
	memcpy (dup, self, sizeof (Gpx2DPoint));
	return dup;
}


void gpx_2d_point_free (Gpx2DPoint* self) {
	g_free (self);
}


GType gpx_2d_point_get_type (void) {
	static volatile gsize gpx_2d_point_type_id__volatile = 0;
	if (g_once_init_enter (&gpx_2d_point_type_id__volatile)) {
		GType gpx_2d_point_type_id;
		gpx_2d_point_type_id = g_boxed_type_register_static ("Gpx2DPoint", (GBoxedCopyFunc) gpx_2d_point_dup, (GBoxedFreeFunc) gpx_2d_point_free);
		g_once_init_leave (&gpx_2d_point_type_id__volatile, gpx_2d_point_type_id);
	}
	return gpx_2d_point_type_id__volatile;
}


Gpxgraph_sizes_t* gpx_graph_sizes_t_dup (const Gpxgraph_sizes_t* self) {
	Gpxgraph_sizes_t* dup;
	dup = g_new0 (Gpxgraph_sizes_t, 1);
	memcpy (dup, self, sizeof (Gpxgraph_sizes_t));
	return dup;
}


void gpx_graph_sizes_t_free (Gpxgraph_sizes_t* self) {
	g_free (self);
}


GType gpx_graph_sizes_t_get_type (void) {
	static volatile gsize gpx_graph_sizes_t_type_id__volatile = 0;
	if (g_once_init_enter (&gpx_graph_sizes_t_type_id__volatile)) {
		GType gpx_graph_sizes_t_type_id;
		gpx_graph_sizes_t_type_id = g_boxed_type_register_static ("Gpxgraph_sizes_t", (GBoxedCopyFunc) gpx_graph_sizes_t_dup, (GBoxedFreeFunc) gpx_graph_sizes_t_free);
		g_once_init_leave (&gpx_graph_sizes_t_type_id__volatile, gpx_graph_sizes_t_type_id);
	}
	return gpx_graph_sizes_t_type_id__volatile;
}


static void _vala_PangoFontDescription_free (PangoFontDescription* self) {
	g_boxed_free (pango_font_description_get_type (), self);
}


gboolean gpx_graph2_view_add_data (GpxGraph2View* self, GeeArrayList* data, gint axis_position, GdkRGBA* color, GdkRGBA* fill) {
	gboolean result = FALSE;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GdkRGBA _tmp3_ = {0};
	GdkRGBA* _tmp4_ = NULL;
	GpxGraph2ViewData* _tmp5_ = NULL;
	GpxGraph2ViewData* _tmp6_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (data != NULL, FALSE);
	g_return_val_if_fail (color != NULL, FALSE);
	_tmp0_ = self->_data;
	_tmp1_ = data;
	_tmp2_ = axis_position;
	_tmp3_ = *color;
	_tmp4_ = fill;
	_tmp5_ = gpx_graph2_view_data_new (_tmp1_, _tmp2_, &_tmp3_, _tmp4_);
	_tmp6_ = _tmp5_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp6_);
	_gpx_graph2_view_data_unref0 (_tmp6_);
	result = TRUE;
	return result;
}


void gpx_graph2_view_plot (GpxGraph2View* self) {
	g_return_if_fail (self != NULL);
	_cairo_surface_destroy0 (self->priv->surf);
	self->priv->surf = NULL;
	gtk_widget_queue_draw ((GtkWidget*) self);
}


static void _gpx_graph2_view_size_allocate_cb_gtk_widget_size_allocate (GtkWidget* _sender, GtkAllocation* allocation, gpointer self) {
	gpx_graph2_view_size_allocate_cb ((GpxGraph2View*) self, allocation);
}


static gboolean _gpx_graph2_view_button_press_event_cb_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = gpx_graph2_view_button_press_event_cb ((GpxGraph2View*) self, event);
	return result;
}


static gboolean _gpx_graph2_view_motion_notify_event_cb_gtk_widget_motion_notify_event (GtkWidget* _sender, GdkEventMotion* event, gpointer self) {
	gboolean result;
	result = gpx_graph2_view_motion_notify_event_cb ((GpxGraph2View*) self, event);
	return result;
}


static gboolean _gpx_graph2_view_button_release_event_cb_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = gpx_graph2_view_button_release_event_cb ((GpxGraph2View*) self, event);
	return result;
}


static gboolean _gpx_graph2_view_expose_cb_gtk_widget_draw (GtkWidget* _sender, cairo_t* cr, gpointer self) {
	gboolean result;
	result = gpx_graph2_view_expose_cb ((GpxGraph2View*) self, cr);
	return result;
}


GpxGraph2View* gpx_graph2_view_construct (GType object_type) {
	GpxGraph2View * self = NULL;
	PangoFontDescription* _tmp0_ = NULL;
	PangoFontDescription* _tmp1_ = NULL;
	GdkRGBA _tmp2_ = {0};
	GdkRGBA _tmp3_ = {0};
	GdkRGBA _tmp4_ = {0};
	GdkRGBA _tmp5_ = {0};
	GdkRGBA _tmp6_ = {0};
	self = (GpxGraph2View*) g_object_new (object_type, NULL);
	_tmp0_ = pango_font_description_new ();
	__vala_PangoFontDescription_free0 (self->priv->fd);
	self->priv->fd = _tmp0_;
	_tmp1_ = self->priv->fd;
	pango_font_description_set_family (_tmp1_, "Cantarell sans mono");
	gtk_widget_set_app_paintable ((GtkWidget*) self, TRUE);
	gtk_event_box_set_visible_window ((GtkEventBox*) self, TRUE);
	g_signal_connect_object ((GtkWidget*) self, "size-allocate", (GCallback) _gpx_graph2_view_size_allocate_cb_gtk_widget_size_allocate, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "button-press-event", (GCallback) _gpx_graph2_view_button_press_event_cb_gtk_widget_button_press_event, self, 0);
	gtk_widget_add_events ((GtkWidget*) self, (gint) GDK_POINTER_MOTION_MASK);
	g_signal_connect_object ((GtkWidget*) self, "motion-notify-event", (GCallback) _gpx_graph2_view_motion_notify_event_cb_gtk_widget_motion_notify_event, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "button-release-event", (GCallback) _gpx_graph2_view_button_release_event_cb_gtk_widget_button_release_event, self, 0);
	_tmp2_.red = 0.9;
	_tmp2_.green = 0.9;
	_tmp2_.blue = 0.9;
	_tmp2_.alpha = (gdouble) 1;
	self->priv->GRID_STRONG = _tmp2_;
	_tmp3_.red = 0.95;
	_tmp3_.green = 0.95;
	_tmp3_.blue = 0.95;
	_tmp3_.alpha = (gdouble) 1;
	self->priv->GRID_LIGHT = _tmp3_;
	_tmp4_.red = 0.999;
	_tmp4_.green = 0.999;
	_tmp4_.blue = 0.999;
	_tmp4_.alpha = (gdouble) 1;
	self->priv->BACKGROUND = _tmp4_;
	_tmp5_.red = 0.7;
	_tmp5_.green = 0.7;
	_tmp5_.blue = 0.7;
	_tmp5_.alpha = (gdouble) 1;
	self->priv->BACKDROP = _tmp5_;
	_tmp6_.red = (gdouble) 0;
	_tmp6_.green = (gdouble) 0;
	_tmp6_.blue = (gdouble) 0;
	_tmp6_.alpha = (gdouble) 1;
	self->priv->X_AXIS_COLOR = _tmp6_;
	g_signal_connect_object ((GtkWidget*) self, "draw", (GCallback) _gpx_graph2_view_expose_cb_gtk_widget_draw, self, 0);
	return self;
}


GpxGraph2View* gpx_graph2_view_new (void) {
	return gpx_graph2_view_construct (GPX_TYPE_GRAPH2_VIEW);
}


static gint* _int_dup (gint* self) {
	gint* dup;
	dup = g_new0 (gint, 1);
	memcpy (dup, self, sizeof (gint));
	return dup;
}


static gpointer __int_dup0 (gpointer self) {
	return self ? _int_dup (self) : NULL;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gint* gpx_graph2_view_index_from_x (GpxGraph2View* self, gdouble x) {
	gint* result = NULL;
	GeeArrayList* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	GpxGraph2ViewData* d = NULL;
	GeeArrayList* _tmp5_ = NULL;
	gpointer _tmp6_ = NULL;
	gint s = 0;
	GpxGraph2ViewData* _tmp7_ = NULL;
	GeeArrayList* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	Gpxgraph_sizes_t gs = {0};
	Gpxgraph_sizes_t _tmp11_ = {0};
	gboolean _tmp12_ = FALSE;
	gdouble _tmp13_ = 0.0;
	Gpxgraph_sizes_t _tmp14_ = {0};
	gdouble _tmp15_ = 0.0;
	gint idx = 0;
	gdouble search_x = 0.0;
	gdouble _tmp21_ = 0.0;
	Gpxgraph_sizes_t _tmp22_ = {0};
	gdouble _tmp23_ = 0.0;
	Gpxgraph_sizes_t _tmp24_ = {0};
	gdouble _tmp25_ = 0.0;
	GpxGraph2ViewData* _tmp26_ = NULL;
	Gpx2DPoint _tmp27_ = {0};
	gdouble _tmp28_ = 0.0;
	GpxGraph2ViewData* _tmp29_ = NULL;
	Gpx2DPoint _tmp30_ = {0};
	gdouble _tmp31_ = 0.0;
	gint _tmp49_ = 0;
	gint* _tmp50_ = NULL;
	gint _tmp51_ = 0;
	gint _tmp52_ = 0;
	gboolean _tmp56_ = FALSE;
	gint _tmp57_ = 0;
	gint _tmp58_ = 0;
	gint* _tmp62_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_data;
	_tmp1_ = gee_collection_get_is_empty ((GeeCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		gint _tmp3_ = 0;
		gint* _tmp4_ = NULL;
		_tmp3_ = -1;
		_tmp4_ = __int_dup0 (&_tmp3_);
		result = _tmp4_;
		return result;
	}
	_tmp5_ = self->_data;
	_tmp6_ = gee_list_first ((GeeList*) _tmp5_);
	d = (GpxGraph2ViewData*) _tmp6_;
	_tmp7_ = d;
	_tmp8_ = _tmp7_->points;
	_tmp9_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp8_);
	_tmp10_ = _tmp9_;
	s = _tmp10_;
	gpx_graph2_view_get_graph_sizes (self, &_tmp11_);
	gs = _tmp11_;
	_tmp13_ = x;
	_tmp14_ = gs;
	_tmp15_ = _tmp14_.start_x;
	if (_tmp13_ < _tmp15_) {
		_tmp12_ = TRUE;
	} else {
		gdouble _tmp16_ = 0.0;
		Gpxgraph_sizes_t _tmp17_ = {0};
		gdouble _tmp18_ = 0.0;
		_tmp16_ = x;
		_tmp17_ = gs;
		_tmp18_ = _tmp17_.end_x;
		_tmp12_ = _tmp16_ > _tmp18_;
	}
	if (_tmp12_) {
		gint _tmp19_ = 0;
		gint* _tmp20_ = NULL;
		_tmp19_ = -1;
		_tmp20_ = __int_dup0 (&_tmp19_);
		result = _tmp20_;
		_gpx_graph2_view_data_unref0 (d);
		return result;
	}
	idx = 0;
	_tmp21_ = x;
	_tmp22_ = gs;
	_tmp23_ = _tmp22_.start_x;
	_tmp24_ = gs;
	_tmp25_ = _tmp24_.graph_width;
	_tmp26_ = d;
	_tmp27_ = _tmp26_->max;
	_tmp28_ = _tmp27_.x;
	_tmp29_ = d;
	_tmp30_ = _tmp29_->min;
	_tmp31_ = _tmp30_.x;
	search_x = ((_tmp21_ - _tmp23_) / _tmp25_) * (_tmp28_ - _tmp31_);
	{
		GeeArrayList* _p_list = NULL;
		GpxGraph2ViewData* _tmp32_ = NULL;
		GeeArrayList* _tmp33_ = NULL;
		GeeArrayList* _tmp34_ = NULL;
		gint _p_size = 0;
		GeeArrayList* _tmp35_ = NULL;
		gint _tmp36_ = 0;
		gint _tmp37_ = 0;
		gint _p_index = 0;
		_tmp32_ = d;
		_tmp33_ = _tmp32_->points;
		_tmp34_ = _g_object_ref0 (_tmp33_);
		_p_list = _tmp34_;
		_tmp35_ = _p_list;
		_tmp36_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp35_);
		_tmp37_ = _tmp36_;
		_p_size = _tmp37_;
		_p_index = -1;
		while (TRUE) {
			gint _tmp38_ = 0;
			gint _tmp39_ = 0;
			gint _tmp40_ = 0;
			Gpx2DPoint* p = NULL;
			GeeArrayList* _tmp41_ = NULL;
			gint _tmp42_ = 0;
			gpointer _tmp43_ = NULL;
			Gpx2DPoint* _tmp44_ = NULL;
			gdouble _tmp45_ = 0.0;
			gdouble _tmp46_ = 0.0;
			gint _tmp48_ = 0;
			_tmp38_ = _p_index;
			_p_index = _tmp38_ + 1;
			_tmp39_ = _p_index;
			_tmp40_ = _p_size;
			if (!(_tmp39_ < _tmp40_)) {
				break;
			}
			_tmp41_ = _p_list;
			_tmp42_ = _p_index;
			_tmp43_ = gee_abstract_list_get ((GeeAbstractList*) _tmp41_, _tmp42_);
			p = (Gpx2DPoint*) _tmp43_;
			_tmp44_ = p;
			_tmp45_ = (*_tmp44_).x;
			_tmp46_ = search_x;
			if (_tmp45_ >= _tmp46_) {
				gint* _tmp47_ = NULL;
				_tmp47_ = __int_dup0 (&idx);
				result = _tmp47_;
				_gpx_2d_point_free0 (p);
				_g_object_unref0 (_p_list);
				_gpx_graph2_view_data_unref0 (d);
				return result;
			}
			_tmp48_ = idx;
			idx = _tmp48_ + 1;
			_gpx_2d_point_free0 (p);
		}
		_g_object_unref0 (_p_list);
	}
	_tmp49_ = -1;
	_tmp50_ = __int_dup0 (&_tmp49_);
	result = _tmp50_;
	_gpx_graph2_view_data_unref0 (d);
	return result;
	_tmp51_ = idx;
	_tmp52_ = s;
	if (_tmp51_ == _tmp52_) {
		gint _tmp53_ = 0;
		gint _tmp54_ = 0;
		gint* _tmp55_ = NULL;
		_tmp53_ = s;
		_tmp54_ = _tmp53_ - 1;
		_tmp55_ = __int_dup0 (&_tmp54_);
		result = _tmp55_;
		_gpx_graph2_view_data_unref0 (d);
		return result;
	}
	_tmp57_ = idx;
	_tmp58_ = s;
	if (_tmp57_ > _tmp58_) {
		_tmp56_ = TRUE;
	} else {
		gint _tmp59_ = 0;
		_tmp59_ = idx;
		_tmp56_ = _tmp59_ < 0;
	}
	if (_tmp56_) {
		gint _tmp60_ = 0;
		gint* _tmp61_ = NULL;
		_tmp60_ = -1;
		_tmp61_ = __int_dup0 (&_tmp60_);
		result = _tmp61_;
		_gpx_graph2_view_data_unref0 (d);
		return result;
	}
	_tmp62_ = __int_dup0 (&idx);
	result = _tmp62_;
	_gpx_graph2_view_data_unref0 (d);
	return result;
}


static gboolean gpx_graph2_view_button_release_event_cb (GpxGraph2View* self, GdkEventButton* event) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	result = TRUE;
	return result;
}


static gboolean gpx_graph2_view_button_press_event_cb (GpxGraph2View* self, GdkEventButton* event) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	result = TRUE;
	return result;
}


static gboolean gpx_graph2_view_motion_notify_event_cb (GpxGraph2View* self, GdkEventMotion* event) {
	gboolean result = FALSE;
	GdkEventMotion* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	gint* _tmp2_ = NULL;
	gint* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = event;
	_tmp1_ = _tmp0_->x;
	_tmp2_ = gpx_graph2_view_index_from_x (self, _tmp1_);
	_tmp3_ = _tmp2_;
	self->priv->highlight = *_tmp3_;
	_g_free0 (_tmp3_);
	gpx_graph2_view_plot (self);
	result = TRUE;
	return result;
}


static void gpx_graph2_view_size_allocate_cb (GpxGraph2View* self, GtkAllocation* alloc) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (alloc != NULL);
	_cairo_surface_destroy0 (self->priv->surf);
	self->priv->surf = NULL;
}


static void gpx_graph2_view_update_surface (GpxGraph2View* self, GtkWidget* win) {
	cairo_t* ctx = NULL;
	GtkWidget* _tmp0_ = NULL;
	GdkWindow* _tmp1_ = NULL;
	cairo_t* _tmp2_ = NULL;
	GtkAllocation alloc = {0};
	GtkWidget* _tmp3_ = NULL;
	GtkAllocation _tmp4_ = {0};
	cairo_t* _tmp5_ = NULL;
	cairo_surface_t* _tmp6_ = NULL;
	GtkAllocation _tmp7_ = {0};
	gint _tmp8_ = 0;
	GtkAllocation _tmp9_ = {0};
	gint _tmp10_ = 0;
	cairo_surface_t* _tmp11_ = NULL;
	cairo_surface_t* _tmp12_ = NULL;
	cairo_t* _tmp13_ = NULL;
	cairo_t* _tmp14_ = NULL;
	cairo_t* _tmp15_ = NULL;
	Gpxgraph_sizes_t gs = {0};
	Gpxgraph_sizes_t _tmp16_ = {0};
	PangoLayout* layout = NULL;
	cairo_t* _tmp17_ = NULL;
	PangoLayout* _tmp18_ = NULL;
	cairo_t* _tmp106_ = NULL;
	PangoLayout* _tmp107_ = NULL;
	GtkAllocation _tmp108_ = {0};
	cairo_t* _tmp109_ = NULL;
	PangoLayout* _tmp110_ = NULL;
	GtkAllocation _tmp111_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (win != NULL);
	_tmp0_ = win;
	_tmp1_ = gtk_widget_get_window (_tmp0_);
	_tmp2_ = gdk_cairo_create (_tmp1_);
	ctx = _tmp2_;
	g_log (LOG_DOMAIN, G_LOG_LEVEL_DEBUG, "gpx-graph2.vala:225: Updating surface");
	_tmp3_ = win;
	gtk_widget_get_allocation (_tmp3_, &_tmp4_);
	alloc = _tmp4_;
	_tmp5_ = ctx;
	_tmp6_ = cairo_get_target (_tmp5_);
	_tmp7_ = alloc;
	_tmp8_ = _tmp7_.width;
	_tmp9_ = alloc;
	_tmp10_ = _tmp9_.height;
	_tmp11_ = cairo_surface_create_similar (_tmp6_, CAIRO_CONTENT_COLOR_ALPHA, _tmp8_, _tmp10_);
	_cairo_surface_destroy0 (self->priv->surf);
	self->priv->surf = _tmp11_;
	_tmp12_ = self->priv->surf;
	_tmp13_ = cairo_create (_tmp12_);
	_cairo_destroy0 (ctx);
	ctx = _tmp13_;
	_tmp14_ = ctx;
	cairo_set_source_rgba (_tmp14_, (gdouble) 1, (gdouble) 1, (gdouble) 1, (gdouble) 1);
	_tmp15_ = ctx;
	cairo_paint (_tmp15_);
	gpx_graph2_view_get_graph_sizes (self, &_tmp16_);
	gs = _tmp16_;
	_tmp17_ = ctx;
	_tmp18_ = pango_cairo_create_layout (_tmp17_);
	layout = _tmp18_;
	{
		GeeArrayList* _d_list = NULL;
		GeeArrayList* _tmp19_ = NULL;
		GeeArrayList* _tmp20_ = NULL;
		gint _d_size = 0;
		GeeArrayList* _tmp21_ = NULL;
		gint _tmp22_ = 0;
		gint _tmp23_ = 0;
		gint _d_index = 0;
		_tmp19_ = self->_data;
		_tmp20_ = _g_object_ref0 (_tmp19_);
		_d_list = _tmp20_;
		_tmp21_ = _d_list;
		_tmp22_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp21_);
		_tmp23_ = _tmp22_;
		_d_size = _tmp23_;
		_d_index = -1;
		while (TRUE) {
			gint _tmp24_ = 0;
			gint _tmp25_ = 0;
			gint _tmp26_ = 0;
			GpxGraph2ViewData* d = NULL;
			GeeArrayList* _tmp27_ = NULL;
			gint _tmp28_ = 0;
			gpointer _tmp29_ = NULL;
			cairo_t* _tmp30_ = NULL;
			GpxGraph2ViewData* _tmp31_ = NULL;
			GpxGraph2ViewDatastyle_t _tmp32_ = {0};
			GdkRGBA _tmp33_ = {0};
			cairo_t* _tmp34_ = NULL;
			GpxGraph2ViewData* _tmp35_ = NULL;
			GpxGraph2ViewDatastyle_t _tmp36_ = {0};
			gdouble _tmp37_ = 0.0;
			cairo_t* _tmp38_ = NULL;
			Gpxgraph_sizes_t _tmp39_ = {0};
			gdouble _tmp40_ = 0.0;
			Gpxgraph_sizes_t _tmp41_ = {0};
			gdouble _tmp42_ = 0.0;
			GpxGraph2ViewData* _tmp90_ = NULL;
			GpxGraph2ViewDatastyle_t _tmp91_ = {0};
			GdkRGBA* _tmp92_ = NULL;
			_tmp24_ = _d_index;
			_d_index = _tmp24_ + 1;
			_tmp25_ = _d_index;
			_tmp26_ = _d_size;
			if (!(_tmp25_ < _tmp26_)) {
				break;
			}
			_tmp27_ = _d_list;
			_tmp28_ = _d_index;
			_tmp29_ = gee_abstract_list_get ((GeeAbstractList*) _tmp27_, _tmp28_);
			d = (GpxGraph2ViewData*) _tmp29_;
			_tmp30_ = ctx;
			_tmp31_ = d;
			_tmp32_ = _tmp31_->style;
			_tmp33_ = _tmp32_.color;
			gdk_cairo_set_source_rgba (_tmp30_, &_tmp33_);
			_tmp34_ = ctx;
			_tmp35_ = d;
			_tmp36_ = _tmp35_->style;
			_tmp37_ = _tmp36_.line_width;
			cairo_set_line_width (_tmp34_, _tmp37_);
			_tmp38_ = ctx;
			_tmp39_ = gs;
			_tmp40_ = _tmp39_.start_x;
			_tmp41_ = gs;
			_tmp42_ = _tmp41_.start_y;
			cairo_move_to (_tmp38_, _tmp40_, _tmp42_);
			{
				GeeArrayList* _p_list = NULL;
				GpxGraph2ViewData* _tmp43_ = NULL;
				GeeArrayList* _tmp44_ = NULL;
				GeeArrayList* _tmp45_ = NULL;
				gint _p_size = 0;
				GeeArrayList* _tmp46_ = NULL;
				gint _tmp47_ = 0;
				gint _tmp48_ = 0;
				gint _p_index = 0;
				_tmp43_ = d;
				_tmp44_ = _tmp43_->points;
				_tmp45_ = _g_object_ref0 (_tmp44_);
				_p_list = _tmp45_;
				_tmp46_ = _p_list;
				_tmp47_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp46_);
				_tmp48_ = _tmp47_;
				_p_size = _tmp48_;
				_p_index = -1;
				while (TRUE) {
					gint _tmp49_ = 0;
					gint _tmp50_ = 0;
					gint _tmp51_ = 0;
					Gpx2DPoint p = {0};
					GeeArrayList* _tmp52_ = NULL;
					gint _tmp53_ = 0;
					gpointer _tmp54_ = NULL;
					Gpx2DPoint* _tmp55_ = NULL;
					Gpx2DPoint _tmp56_ = {0};
					gdouble x = 0.0;
					Gpxgraph_sizes_t _tmp57_ = {0};
					gdouble _tmp58_ = 0.0;
					Gpx2DPoint _tmp59_ = {0};
					gdouble _tmp60_ = 0.0;
					GpxGraph2ViewData* _tmp61_ = NULL;
					Gpx2DPoint _tmp62_ = {0};
					gdouble _tmp63_ = 0.0;
					GpxGraph2ViewData* _tmp64_ = NULL;
					Gpx2DPoint _tmp65_ = {0};
					gdouble _tmp66_ = 0.0;
					GpxGraph2ViewData* _tmp67_ = NULL;
					Gpx2DPoint _tmp68_ = {0};
					gdouble _tmp69_ = 0.0;
					Gpxgraph_sizes_t _tmp70_ = {0};
					gdouble _tmp71_ = 0.0;
					gdouble y = 0.0;
					Gpxgraph_sizes_t _tmp72_ = {0};
					gdouble _tmp73_ = 0.0;
					Gpx2DPoint _tmp74_ = {0};
					gdouble _tmp75_ = 0.0;
					GpxGraph2ViewData* _tmp76_ = NULL;
					Gpx2DPoint _tmp77_ = {0};
					gdouble _tmp78_ = 0.0;
					GpxGraph2ViewData* _tmp79_ = NULL;
					Gpx2DPoint _tmp80_ = {0};
					gdouble _tmp81_ = 0.0;
					GpxGraph2ViewData* _tmp82_ = NULL;
					Gpx2DPoint _tmp83_ = {0};
					gdouble _tmp84_ = 0.0;
					Gpxgraph_sizes_t _tmp85_ = {0};
					gdouble _tmp86_ = 0.0;
					cairo_t* _tmp87_ = NULL;
					gdouble _tmp88_ = 0.0;
					gdouble _tmp89_ = 0.0;
					_tmp49_ = _p_index;
					_p_index = _tmp49_ + 1;
					_tmp50_ = _p_index;
					_tmp51_ = _p_size;
					if (!(_tmp50_ < _tmp51_)) {
						break;
					}
					_tmp52_ = _p_list;
					_tmp53_ = _p_index;
					_tmp54_ = gee_abstract_list_get ((GeeAbstractList*) _tmp52_, _tmp53_);
					_tmp55_ = (Gpx2DPoint*) _tmp54_;
					_tmp56_ = *_tmp55_;
					_gpx_2d_point_free0 (_tmp55_);
					p = _tmp56_;
					_tmp57_ = gs;
					_tmp58_ = _tmp57_.start_x;
					_tmp59_ = p;
					_tmp60_ = _tmp59_.x;
					_tmp61_ = d;
					_tmp62_ = _tmp61_->min;
					_tmp63_ = _tmp62_.x;
					_tmp64_ = d;
					_tmp65_ = _tmp64_->max;
					_tmp66_ = _tmp65_.x;
					_tmp67_ = d;
					_tmp68_ = _tmp67_->min;
					_tmp69_ = _tmp68_.x;
					_tmp70_ = gs;
					_tmp71_ = _tmp70_.graph_width;
					x = _tmp58_ + (((_tmp60_ - _tmp63_) / (_tmp66_ - _tmp69_)) * _tmp71_);
					_tmp72_ = gs;
					_tmp73_ = _tmp72_.start_y;
					_tmp74_ = p;
					_tmp75_ = _tmp74_.y;
					_tmp76_ = d;
					_tmp77_ = _tmp76_->min;
					_tmp78_ = _tmp77_.y;
					_tmp79_ = d;
					_tmp80_ = _tmp79_->max;
					_tmp81_ = _tmp80_.y;
					_tmp82_ = d;
					_tmp83_ = _tmp82_->min;
					_tmp84_ = _tmp83_.y;
					_tmp85_ = gs;
					_tmp86_ = _tmp85_.graph_height;
					y = _tmp73_ - (((_tmp75_ - _tmp78_) / (_tmp81_ - _tmp84_)) * _tmp86_);
					_tmp87_ = ctx;
					_tmp88_ = x;
					_tmp89_ = y;
					cairo_line_to (_tmp87_, _tmp88_, _tmp89_);
				}
				_g_object_unref0 (_p_list);
			}
			_tmp90_ = d;
			_tmp91_ = _tmp90_->style;
			_tmp92_ = _tmp91_.fill;
			if (_tmp92_ != NULL) {
				cairo_t* _tmp93_ = NULL;
				cairo_t* _tmp94_ = NULL;
				Gpxgraph_sizes_t _tmp95_ = {0};
				gdouble _tmp96_ = 0.0;
				Gpxgraph_sizes_t _tmp97_ = {0};
				gdouble _tmp98_ = 0.0;
				cairo_t* _tmp99_ = NULL;
				GpxGraph2ViewData* _tmp100_ = NULL;
				GpxGraph2ViewDatastyle_t _tmp101_ = {0};
				GdkRGBA* _tmp102_ = NULL;
				GdkRGBA _tmp103_ = {0};
				cairo_t* _tmp104_ = NULL;
				_tmp93_ = ctx;
				cairo_stroke_preserve (_tmp93_);
				_tmp94_ = ctx;
				_tmp95_ = gs;
				_tmp96_ = _tmp95_.end_x;
				_tmp97_ = gs;
				_tmp98_ = _tmp97_.start_y;
				cairo_line_to (_tmp94_, _tmp96_, _tmp98_);
				_tmp99_ = ctx;
				_tmp100_ = d;
				_tmp101_ = _tmp100_->style;
				_tmp102_ = _tmp101_.fill;
				_tmp103_ = *_tmp102_;
				gdk_cairo_set_source_rgba (_tmp99_, &_tmp103_);
				_tmp104_ = ctx;
				cairo_fill (_tmp104_);
			} else {
				cairo_t* _tmp105_ = NULL;
				_tmp105_ = ctx;
				cairo_stroke (_tmp105_);
			}
			_gpx_graph2_view_data_unref0 (d);
		}
		_g_object_unref0 (_d_list);
	}
	_tmp106_ = ctx;
	_tmp107_ = layout;
	_tmp108_ = alloc;
	gpx_graph2_view_draw_axis (self, _tmp106_, _tmp107_, &_tmp108_);
	_tmp109_ = ctx;
	_tmp110_ = layout;
	_tmp111_ = alloc;
	gpx_graph2_view_draw_highlight (self, _tmp109_, _tmp110_, &_tmp111_);
	_g_object_unref0 (layout);
	_cairo_destroy0 (ctx);
}


static void gpx_graph2_view_draw_highlight (GpxGraph2View* self, cairo_t* ctx, PangoLayout* layout, GtkAllocation* alloc) {
	gint _tmp0_ = 0;
	GeeArrayList* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	GpxGraph2ViewData* df = NULL;
	GeeArrayList* _tmp4_ = NULL;
	gpointer _tmp5_ = NULL;
	Gpxgraph_sizes_t gs = {0};
	Gpxgraph_sizes_t _tmp6_ = {0};
	gdouble x = 0.0;
	Gpxgraph_sizes_t _tmp7_ = {0};
	gdouble _tmp8_ = 0.0;
	GpxGraph2ViewData* _tmp9_ = NULL;
	GeeArrayList* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	gpointer _tmp12_ = NULL;
	Gpx2DPoint* _tmp13_ = NULL;
	gdouble _tmp14_ = 0.0;
	GpxGraph2ViewData* _tmp15_ = NULL;
	Gpx2DPoint _tmp16_ = {0};
	gdouble _tmp17_ = 0.0;
	GpxGraph2ViewData* _tmp18_ = NULL;
	Gpx2DPoint _tmp19_ = {0};
	gdouble _tmp20_ = 0.0;
	GpxGraph2ViewData* _tmp21_ = NULL;
	Gpx2DPoint _tmp22_ = {0};
	gdouble _tmp23_ = 0.0;
	Gpxgraph_sizes_t _tmp24_ = {0};
	gdouble _tmp25_ = 0.0;
	gdouble _tmp26_ = 0.0;
	cairo_t* _tmp27_ = NULL;
	cairo_t* _tmp28_ = NULL;
	gdouble _tmp29_ = 0.0;
	Gpxgraph_sizes_t _tmp30_ = {0};
	gdouble _tmp31_ = 0.0;
	cairo_t* _tmp32_ = NULL;
	gdouble _tmp33_ = 0.0;
	Gpxgraph_sizes_t _tmp34_ = {0};
	gdouble _tmp35_ = 0.0;
	cairo_t* _tmp36_ = NULL;
	PangoFontDescription* _tmp37_ = NULL;
	PangoLayout* _tmp38_ = NULL;
	PangoFontDescription* _tmp39_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (ctx != NULL);
	g_return_if_fail (layout != NULL);
	g_return_if_fail (alloc != NULL);
	_tmp0_ = self->priv->highlight;
	if (_tmp0_ < 0) {
		return;
	}
	_tmp1_ = self->_data;
	_tmp2_ = gee_collection_get_is_empty ((GeeCollection*) _tmp1_);
	_tmp3_ = _tmp2_;
	if (_tmp3_) {
		return;
	}
	_tmp4_ = self->_data;
	_tmp5_ = gee_list_first ((GeeList*) _tmp4_);
	df = (GpxGraph2ViewData*) _tmp5_;
	gpx_graph2_view_get_graph_sizes (self, &_tmp6_);
	gs = _tmp6_;
	_tmp7_ = gs;
	_tmp8_ = _tmp7_.start_x;
	_tmp9_ = df;
	_tmp10_ = _tmp9_->points;
	_tmp11_ = self->priv->highlight;
	_tmp12_ = gee_abstract_list_get ((GeeAbstractList*) _tmp10_, _tmp11_);
	_tmp13_ = (Gpx2DPoint*) _tmp12_;
	_tmp14_ = (*_tmp13_).x;
	_tmp15_ = df;
	_tmp16_ = _tmp15_->min;
	_tmp17_ = _tmp16_.x;
	_tmp18_ = df;
	_tmp19_ = _tmp18_->max;
	_tmp20_ = _tmp19_.x;
	_tmp21_ = df;
	_tmp22_ = _tmp21_->min;
	_tmp23_ = _tmp22_.x;
	_tmp24_ = gs;
	_tmp25_ = _tmp24_.graph_width;
	_tmp26_ = _tmp8_ + (((_tmp14_ - _tmp17_) / (_tmp20_ - _tmp23_)) * _tmp25_);
	_gpx_2d_point_free0 (_tmp13_);
	x = _tmp26_;
	_tmp27_ = ctx;
	cairo_set_source_rgba (_tmp27_, (gdouble) 1, (gdouble) 0, (gdouble) 0, (gdouble) 1);
	_tmp28_ = ctx;
	_tmp29_ = x;
	_tmp30_ = gs;
	_tmp31_ = _tmp30_.start_y;
	cairo_move_to (_tmp28_, _tmp29_, _tmp31_);
	_tmp32_ = ctx;
	_tmp33_ = x;
	_tmp34_ = gs;
	_tmp35_ = _tmp34_.end_y;
	cairo_line_to (_tmp32_, _tmp33_, _tmp35_);
	_tmp36_ = ctx;
	cairo_stroke (_tmp36_);
	_tmp37_ = self->priv->fd;
	pango_font_description_set_absolute_size (_tmp37_, (gdouble) (9 * 1024));
	_tmp38_ = layout;
	_tmp39_ = self->priv->fd;
	pango_layout_set_font_description (_tmp38_, _tmp39_);
	{
		GeeArrayList* _d_list = NULL;
		GeeArrayList* _tmp40_ = NULL;
		GeeArrayList* _tmp41_ = NULL;
		gint _d_size = 0;
		GeeArrayList* _tmp42_ = NULL;
		gint _tmp43_ = 0;
		gint _tmp44_ = 0;
		gint _d_index = 0;
		_tmp40_ = self->_data;
		_tmp41_ = _g_object_ref0 (_tmp40_);
		_d_list = _tmp41_;
		_tmp42_ = _d_list;
		_tmp43_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp42_);
		_tmp44_ = _tmp43_;
		_d_size = _tmp44_;
		_d_index = -1;
		while (TRUE) {
			gint _tmp45_ = 0;
			gint _tmp46_ = 0;
			gint _tmp47_ = 0;
			GpxGraph2ViewData* d = NULL;
			GeeArrayList* _tmp48_ = NULL;
			gint _tmp49_ = 0;
			gpointer _tmp50_ = NULL;
			gdouble y = 0.0;
			Gpxgraph_sizes_t _tmp51_ = {0};
			gdouble _tmp52_ = 0.0;
			GpxGraph2ViewData* _tmp53_ = NULL;
			GeeArrayList* _tmp54_ = NULL;
			gint _tmp55_ = 0;
			gpointer _tmp56_ = NULL;
			Gpx2DPoint* _tmp57_ = NULL;
			gdouble _tmp58_ = 0.0;
			GpxGraph2ViewData* _tmp59_ = NULL;
			Gpx2DPoint _tmp60_ = {0};
			gdouble _tmp61_ = 0.0;
			GpxGraph2ViewData* _tmp62_ = NULL;
			Gpx2DPoint _tmp63_ = {0};
			gdouble _tmp64_ = 0.0;
			GpxGraph2ViewData* _tmp65_ = NULL;
			Gpx2DPoint _tmp66_ = {0};
			gdouble _tmp67_ = 0.0;
			Gpxgraph_sizes_t _tmp68_ = {0};
			gdouble _tmp69_ = 0.0;
			gdouble _tmp70_ = 0.0;
			gint _tmp71_ = 0;
			GpxGraph2ViewData* _tmp72_ = NULL;
			GeeArrayList* _tmp73_ = NULL;
			gint _tmp74_ = 0;
			gpointer _tmp75_ = NULL;
			Gpx2DPoint* _tmp76_ = NULL;
			gdouble _tmp77_ = 0.0;
			cairo_t* _tmp78_ = NULL;
			GpxGraph2ViewData* _tmp79_ = NULL;
			GpxGraph2ViewDatastyle_t _tmp80_ = {0};
			GdkRGBA _tmp81_ = {0};
			cairo_t* _tmp82_ = NULL;
			gdouble _tmp83_ = 0.0;
			gdouble _tmp84_ = 0.0;
			cairo_t* _tmp85_ = NULL;
			gdouble at_x = 0.0;
			GpxGraph2ViewData* _tmp86_ = NULL;
			gint _tmp87_ = 0;
			_tmp45_ = _d_index;
			_d_index = _tmp45_ + 1;
			_tmp46_ = _d_index;
			_tmp47_ = _d_size;
			if (!(_tmp46_ < _tmp47_)) {
				break;
			}
			_tmp48_ = _d_list;
			_tmp49_ = _d_index;
			_tmp50_ = gee_abstract_list_get ((GeeAbstractList*) _tmp48_, _tmp49_);
			d = (GpxGraph2ViewData*) _tmp50_;
			_tmp51_ = gs;
			_tmp52_ = _tmp51_.start_y;
			_tmp53_ = d;
			_tmp54_ = _tmp53_->points;
			_tmp55_ = self->priv->highlight;
			_tmp56_ = gee_abstract_list_get ((GeeAbstractList*) _tmp54_, _tmp55_);
			_tmp57_ = (Gpx2DPoint*) _tmp56_;
			_tmp58_ = (*_tmp57_).y;
			_tmp59_ = d;
			_tmp60_ = _tmp59_->min;
			_tmp61_ = _tmp60_.y;
			_tmp62_ = d;
			_tmp63_ = _tmp62_->max;
			_tmp64_ = _tmp63_.y;
			_tmp65_ = d;
			_tmp66_ = _tmp65_->min;
			_tmp67_ = _tmp66_.y;
			_tmp68_ = gs;
			_tmp69_ = _tmp68_.graph_height;
			_tmp70_ = _tmp52_ - (((_tmp58_ - _tmp61_) / (_tmp64_ - _tmp67_)) * _tmp69_);
			_gpx_2d_point_free0 (_tmp57_);
			y = _tmp70_;
			_tmp71_ = self->priv->highlight;
			_tmp72_ = d;
			_tmp73_ = _tmp72_->points;
			_tmp74_ = self->priv->highlight;
			_tmp75_ = gee_abstract_list_get ((GeeAbstractList*) _tmp73_, _tmp74_);
			_tmp76_ = (Gpx2DPoint*) _tmp75_;
			_tmp77_ = (*_tmp76_).y;
			g_print ("hi: %i, %f\n", _tmp71_, _tmp77_);
			_gpx_2d_point_free0 (_tmp76_);
			_tmp78_ = ctx;
			_tmp79_ = d;
			_tmp80_ = _tmp79_->style;
			_tmp81_ = _tmp80_.color;
			gdk_cairo_set_source_rgba (_tmp78_, &_tmp81_);
			_tmp82_ = ctx;
			_tmp83_ = x;
			_tmp84_ = y;
			cairo_rectangle (_tmp82_, _tmp83_ - 2, _tmp84_ - 2, (gdouble) 4, (gdouble) 4);
			_tmp85_ = ctx;
			cairo_stroke (_tmp85_);
			at_x = (gdouble) 0;
			_tmp86_ = d;
			_tmp87_ = _tmp86_->axis_position;
			if (_tmp87_ > 0) {
				Gpxgraph_sizes_t _tmp88_ = {0};
				gdouble _tmp89_ = 0.0;
				GpxGraph2ViewData* _tmp90_ = NULL;
				gint _tmp91_ = 0;
				gint _tmp92_ = 0;
				_tmp88_ = gs;
				_tmp89_ = _tmp88_.end_x;
				_tmp90_ = d;
				_tmp91_ = _tmp90_->axis_position;
				_tmp92_ = self->priv->AXIS_MARGIN;
				at_x = _tmp89_ + ((_tmp91_ - 1) * _tmp92_);
			} else {
				Gpxgraph_sizes_t _tmp93_ = {0};
				gdouble _tmp94_ = 0.0;
				GpxGraph2ViewData* _tmp95_ = NULL;
				gint _tmp96_ = 0;
				gint _tmp97_ = 0;
				cairo_t* _tmp98_ = NULL;
				gdouble _tmp99_ = 0.0;
				gdouble _tmp100_ = 0.0;
				cairo_t* _tmp101_ = NULL;
				gdouble _tmp102_ = 0.0;
				gdouble _tmp103_ = 0.0;
				gint w = 0;
				gint h = 0;
				gdouble unit = 0.0;
				GpxGraph2ViewData* _tmp104_ = NULL;
				GeeArrayList* _tmp105_ = NULL;
				gint _tmp106_ = 0;
				gpointer _tmp107_ = NULL;
				Gpx2DPoint* _tmp108_ = NULL;
				gdouble _tmp109_ = 0.0;
				gdouble _tmp110_ = 0.0;
				gchar* markup = NULL;
				const gchar* _tmp111_ = NULL;
				gdouble _tmp112_ = 0.0;
				gchar* _tmp113_ = NULL;
				PangoLayout* _tmp114_ = NULL;
				const gchar* _tmp115_ = NULL;
				PangoLayout* _tmp116_ = NULL;
				gint _tmp117_ = 0;
				gint _tmp118_ = 0;
				gint _tmp119_ = 0;
				gint _tmp120_ = 0;
				gint width = 0;
				cairo_t* _tmp122_ = NULL;
				gdouble _tmp123_ = 0.0;
				gint _tmp124_ = 0;
				gdouble _tmp125_ = 0.0;
				cairo_t* _tmp126_ = NULL;
				gdouble _tmp127_ = 0.0;
				gint _tmp128_ = 0;
				gdouble _tmp129_ = 0.0;
				cairo_t* _tmp130_ = NULL;
				gdouble _tmp131_ = 0.0;
				gdouble _tmp132_ = 0.0;
				cairo_t* _tmp133_ = NULL;
				cairo_t* _tmp134_ = NULL;
				cairo_t* _tmp135_ = NULL;
				gdouble _tmp136_ = 0.0;
				gint _tmp137_ = 0;
				gdouble _tmp138_ = 0.0;
				gint _tmp139_ = 0;
				cairo_t* _tmp140_ = NULL;
				PangoLayout* _tmp141_ = NULL;
				cairo_t* _tmp142_ = NULL;
				_tmp93_ = gs;
				_tmp94_ = _tmp93_.start_x;
				_tmp95_ = d;
				_tmp96_ = _tmp95_->axis_position;
				_tmp97_ = self->priv->AXIS_MARGIN;
				at_x = _tmp94_ + ((_tmp96_ + 1) * _tmp97_);
				_tmp98_ = ctx;
				_tmp99_ = at_x;
				_tmp100_ = y;
				cairo_move_to (_tmp98_, _tmp99_, _tmp100_);
				_tmp101_ = ctx;
				_tmp102_ = at_x;
				_tmp103_ = y;
				cairo_line_to (_tmp101_, _tmp102_ - 8, _tmp103_ - 8);
				_tmp104_ = d;
				_tmp105_ = _tmp104_->points;
				_tmp106_ = self->priv->highlight;
				_tmp107_ = gee_abstract_list_get ((GeeAbstractList*) _tmp105_, _tmp106_);
				_tmp108_ = (Gpx2DPoint*) _tmp107_;
				_tmp109_ = (*_tmp108_).y;
				_tmp110_ = _tmp109_;
				_gpx_2d_point_free0 (_tmp108_);
				unit = _tmp110_;
				_tmp111_ = _ ("<b>%.1f</b>");
				_tmp112_ = unit;
				_tmp113_ = g_strdup_printf (_tmp111_, _tmp112_);
				markup = _tmp113_;
				_tmp114_ = layout;
				_tmp115_ = markup;
				pango_layout_set_markup (_tmp114_, _tmp115_, -1);
				_tmp116_ = layout;
				pango_layout_get_pixel_size (_tmp116_, &_tmp117_, &_tmp118_);
				w = _tmp117_;
				h = _tmp118_;
				_tmp120_ = w;
				if (_tmp120_ > 30) {
					gint _tmp121_ = 0;
					_tmp121_ = w;
					_tmp119_ = _tmp121_ + 5;
				} else {
					_tmp119_ = 30;
				}
				width = _tmp119_;
				_tmp122_ = ctx;
				_tmp123_ = at_x;
				_tmp124_ = width;
				_tmp125_ = y;
				cairo_line_to (_tmp122_, (_tmp123_ - 8) - _tmp124_, _tmp125_ - 8);
				_tmp126_ = ctx;
				_tmp127_ = at_x;
				_tmp128_ = width;
				_tmp129_ = y;
				cairo_line_to (_tmp126_, (_tmp127_ - 8) - _tmp128_, _tmp129_ + 8);
				_tmp130_ = ctx;
				_tmp131_ = at_x;
				_tmp132_ = y;
				cairo_line_to (_tmp130_, _tmp131_ - 8, _tmp132_ + 8);
				_tmp133_ = ctx;
				cairo_fill (_tmp133_);
				_tmp134_ = ctx;
				cairo_set_source_rgba (_tmp134_, (gdouble) 1, (gdouble) 1, (gdouble) 1, (gdouble) 1);
				_tmp135_ = ctx;
				_tmp136_ = at_x;
				_tmp137_ = width;
				_tmp138_ = y;
				_tmp139_ = h;
				cairo_move_to (_tmp135_, (_tmp136_ - _tmp137_) - 3.5, (_tmp138_ - (_tmp139_ / 2)) + 0.5);
				_tmp140_ = ctx;
				_tmp141_ = layout;
				pango_cairo_layout_path (_tmp140_, _tmp141_);
				_tmp142_ = ctx;
				cairo_fill (_tmp142_);
				_g_free0 (markup);
			}
			_gpx_graph2_view_data_unref0 (d);
		}
		_g_object_unref0 (_d_list);
	}
	_gpx_graph2_view_data_unref0 (df);
}


static void gpx_graph2_view_get_graph_sizes (GpxGraph2View* self, Gpxgraph_sizes_t* result) {
	GtkAllocation alloc = {0};
	GtkAllocation _tmp0_ = {0};
	Gpxgraph_sizes_t ret_val = {0};
	GtkAllocation _tmp1_ = {0};
	gint _tmp2_ = 0;
	GtkAllocation _tmp3_ = {0};
	gint _tmp4_ = 0;
	Gpxgraph_sizes_t _tmp5_ = {0};
	gdouble _tmp6_ = 0.0;
	gdouble _tmp7_ = 0.0;
	gdouble _tmp8_ = 0.0;
	Gpxgraph_sizes_t _tmp9_ = {0};
	gdouble _tmp10_ = 0.0;
	gdouble _tmp11_ = 0.0;
	gdouble _tmp12_ = 0.0;
	gdouble _tmp13_ = 0.0;
	Gpxgraph_sizes_t _tmp14_ = {0};
	gdouble _tmp15_ = 0.0;
	gdouble _tmp16_ = 0.0;
	Gpxgraph_sizes_t _tmp17_ = {0};
	gdouble _tmp18_ = 0.0;
	gdouble _tmp19_ = 0.0;
	gdouble _tmp20_ = 0.0;
	g_return_if_fail (self != NULL);
	gtk_widget_get_allocation ((GtkWidget*) self, &_tmp0_);
	alloc = _tmp0_;
	memset (&ret_val, 0, sizeof (Gpxgraph_sizes_t));
	_tmp1_ = alloc;
	_tmp2_ = _tmp1_.width;
	ret_val.alloc_width = (gdouble) _tmp2_;
	_tmp3_ = alloc;
	_tmp4_ = _tmp3_.height;
	ret_val.alloc_height = (gdouble) _tmp4_;
	_tmp5_ = ret_val;
	_tmp6_ = _tmp5_.alloc_width;
	_tmp7_ = self->priv->OFFSET_LEFT;
	_tmp8_ = self->priv->OFFSET_RIGHT;
	ret_val.graph_width = (_tmp6_ - _tmp7_) - _tmp8_;
	_tmp9_ = ret_val;
	_tmp10_ = _tmp9_.alloc_height;
	_tmp11_ = self->priv->OFFSET_TOP;
	_tmp12_ = self->priv->OFFSET_BOTTOM;
	ret_val.graph_height = (_tmp10_ - _tmp11_) - _tmp12_;
	_tmp13_ = self->priv->OFFSET_LEFT;
	ret_val.start_x = _tmp13_;
	_tmp14_ = ret_val;
	_tmp15_ = _tmp14_.graph_width;
	_tmp16_ = self->priv->OFFSET_LEFT;
	ret_val.end_x = _tmp15_ + _tmp16_;
	_tmp17_ = ret_val;
	_tmp18_ = _tmp17_.alloc_height;
	_tmp19_ = self->priv->OFFSET_BOTTOM;
	ret_val.start_y = _tmp18_ - _tmp19_;
	_tmp20_ = self->priv->OFFSET_TOP;
	ret_val.end_y = _tmp20_;
	*result = ret_val;
	return;
}


static void gpx_graph2_view_draw_axis (GpxGraph2View* self, cairo_t* ctx, PangoLayout* layout, GtkAllocation* alloc) {
	GeeArrayList* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	GpxGraph2ViewData* d = NULL;
	GeeArrayList* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gdouble xmax = 0.0;
	GpxGraph2ViewData* _tmp5_ = NULL;
	Gpx2DPoint _tmp6_ = {0};
	gdouble _tmp7_ = 0.0;
	gdouble xmin = 0.0;
	GpxGraph2ViewData* _tmp8_ = NULL;
	Gpx2DPoint _tmp9_ = {0};
	gdouble _tmp10_ = 0.0;
	Gpxgraph_sizes_t gs = {0};
	Gpxgraph_sizes_t _tmp11_ = {0};
	cairo_t* _tmp12_ = NULL;
	GdkRGBA _tmp13_ = {0};
	cairo_t* _tmp14_ = NULL;
	Gpxgraph_sizes_t _tmp15_ = {0};
	gdouble _tmp16_ = 0.0;
	Gpxgraph_sizes_t _tmp17_ = {0};
	gdouble _tmp18_ = 0.0;
	cairo_t* _tmp19_ = NULL;
	Gpxgraph_sizes_t _tmp20_ = {0};
	gdouble _tmp21_ = 0.0;
	Gpxgraph_sizes_t _tmp22_ = {0};
	gdouble _tmp23_ = 0.0;
	cairo_t* _tmp24_ = NULL;
	gfloat steps = 0.0F;
	gint idx = 0;
	gint x_stepsize = 0;
	Gpxgraph_sizes_t _tmp25_ = {0};
	gdouble _tmp26_ = 0.0;
	gfloat _tmp27_ = 0.0F;
	cairo_t* _tmp51_ = NULL;
	cairo_t* _tmp52_ = NULL;
	cairo_t* _tmp70_ = NULL;
	PangoFontDescription* _tmp71_ = NULL;
	PangoLayout* _tmp72_ = NULL;
	PangoFontDescription* _tmp73_ = NULL;
	gdouble y_stepsize = 0.0;
	Gpxgraph_sizes_t _tmp113_ = {0};
	gdouble _tmp114_ = 0.0;
	cairo_t* _tmp210_ = NULL;
	cairo_t* _tmp228_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (ctx != NULL);
	g_return_if_fail (layout != NULL);
	g_return_if_fail (alloc != NULL);
	_tmp0_ = self->_data;
	_tmp1_ = gee_collection_get_is_empty ((GeeCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		return;
	}
	_tmp3_ = self->_data;
	_tmp4_ = gee_list_first ((GeeList*) _tmp3_);
	d = (GpxGraph2ViewData*) _tmp4_;
	_tmp5_ = d;
	_tmp6_ = _tmp5_->max;
	_tmp7_ = _tmp6_.x;
	xmax = _tmp7_;
	_tmp8_ = d;
	_tmp9_ = _tmp8_->max;
	_tmp10_ = _tmp9_.y;
	xmin = _tmp10_;
	gpx_graph2_view_get_graph_sizes (self, &_tmp11_);
	gs = _tmp11_;
	_tmp12_ = ctx;
	_tmp13_ = self->priv->X_AXIS_COLOR;
	gdk_cairo_set_source_rgba (_tmp12_, &_tmp13_);
	_tmp14_ = ctx;
	_tmp15_ = gs;
	_tmp16_ = _tmp15_.start_x;
	_tmp17_ = gs;
	_tmp18_ = _tmp17_.start_y;
	cairo_move_to (_tmp14_, _tmp16_, _tmp18_);
	_tmp19_ = ctx;
	_tmp20_ = gs;
	_tmp21_ = _tmp20_.end_x;
	_tmp22_ = gs;
	_tmp23_ = _tmp22_.start_y;
	cairo_line_to (_tmp19_, _tmp21_, _tmp23_);
	_tmp24_ = ctx;
	cairo_stroke (_tmp24_);
	steps = 16.0f;
	idx = 1;
	_tmp25_ = gs;
	_tmp26_ = _tmp25_.graph_width;
	_tmp27_ = steps;
	x_stepsize = (gint) (_tmp26_ / _tmp27_);
	{
		gdouble x_dash = 0.0;
		Gpxgraph_sizes_t _tmp28_ = {0};
		gdouble _tmp29_ = 0.0;
		gint _tmp30_ = 0;
		_tmp28_ = gs;
		_tmp29_ = _tmp28_.start_x;
		_tmp30_ = x_stepsize;
		x_dash = _tmp29_ + _tmp30_;
		{
			gboolean _tmp31_ = FALSE;
			_tmp31_ = TRUE;
			while (TRUE) {
				gdouble _tmp34_ = 0.0;
				Gpxgraph_sizes_t _tmp35_ = {0};
				gdouble _tmp36_ = 0.0;
				gint _tmp37_ = 0;
				cairo_t* _tmp42_ = NULL;
				gdouble _tmp43_ = 0.0;
				Gpxgraph_sizes_t _tmp44_ = {0};
				gdouble _tmp45_ = 0.0;
				cairo_t* _tmp46_ = NULL;
				gdouble _tmp47_ = 0.0;
				Gpxgraph_sizes_t _tmp48_ = {0};
				gdouble _tmp49_ = 0.0;
				gint _tmp50_ = 0;
				if (!_tmp31_) {
					gdouble _tmp32_ = 0.0;
					gint _tmp33_ = 0;
					_tmp32_ = x_dash;
					_tmp33_ = x_stepsize;
					x_dash = _tmp32_ + _tmp33_;
				}
				_tmp31_ = FALSE;
				_tmp34_ = x_dash;
				_tmp35_ = gs;
				_tmp36_ = _tmp35_.end_x;
				if (!(_tmp34_ <= _tmp36_)) {
					break;
				}
				_tmp37_ = idx;
				if ((_tmp37_ % 2) == 0) {
					cairo_t* _tmp38_ = NULL;
					GdkRGBA _tmp39_ = {0};
					_tmp38_ = ctx;
					_tmp39_ = self->priv->GRID_LIGHT;
					gdk_cairo_set_source_rgba (_tmp38_, &_tmp39_);
				} else {
					cairo_t* _tmp40_ = NULL;
					GdkRGBA _tmp41_ = {0};
					_tmp40_ = ctx;
					_tmp41_ = self->priv->GRID_STRONG;
					gdk_cairo_set_source_rgba (_tmp40_, &_tmp41_);
				}
				_tmp42_ = ctx;
				_tmp43_ = x_dash;
				_tmp44_ = gs;
				_tmp45_ = _tmp44_.start_y;
				cairo_move_to (_tmp42_, _tmp43_, _tmp45_ + 5);
				_tmp46_ = ctx;
				_tmp47_ = x_dash;
				_tmp48_ = gs;
				_tmp49_ = _tmp48_.start_y;
				cairo_line_to (_tmp46_, _tmp47_, _tmp49_);
				_tmp50_ = idx;
				idx = _tmp50_ + 1;
			}
		}
	}
	_tmp51_ = ctx;
	cairo_stroke (_tmp51_);
	_tmp52_ = ctx;
	cairo_set_source_rgba (_tmp52_, (gdouble) 0, (gdouble) 0, (gdouble) 0, 0.5);
	{
		gdouble x_dash = 0.0;
		Gpxgraph_sizes_t _tmp53_ = {0};
		gdouble _tmp54_ = 0.0;
		gint _tmp55_ = 0;
		_tmp53_ = gs;
		_tmp54_ = _tmp53_.start_x;
		_tmp55_ = x_stepsize;
		x_dash = _tmp54_ + _tmp55_;
		{
			gboolean _tmp56_ = FALSE;
			_tmp56_ = TRUE;
			while (TRUE) {
				gdouble _tmp59_ = 0.0;
				Gpxgraph_sizes_t _tmp60_ = {0};
				gdouble _tmp61_ = 0.0;
				cairo_t* _tmp62_ = NULL;
				gdouble _tmp63_ = 0.0;
				Gpxgraph_sizes_t _tmp64_ = {0};
				gdouble _tmp65_ = 0.0;
				cairo_t* _tmp66_ = NULL;
				gdouble _tmp67_ = 0.0;
				Gpxgraph_sizes_t _tmp68_ = {0};
				gdouble _tmp69_ = 0.0;
				if (!_tmp56_) {
					gdouble _tmp57_ = 0.0;
					gint _tmp58_ = 0;
					_tmp57_ = x_dash;
					_tmp58_ = x_stepsize;
					x_dash = _tmp57_ + _tmp58_;
				}
				_tmp56_ = FALSE;
				_tmp59_ = x_dash;
				_tmp60_ = gs;
				_tmp61_ = _tmp60_.end_x;
				if (!(_tmp59_ <= _tmp61_)) {
					break;
				}
				_tmp62_ = ctx;
				_tmp63_ = x_dash;
				_tmp64_ = gs;
				_tmp65_ = _tmp64_.start_y;
				cairo_move_to (_tmp62_, _tmp63_, _tmp65_);
				_tmp66_ = ctx;
				_tmp67_ = x_dash;
				_tmp68_ = gs;
				_tmp69_ = _tmp68_.end_y;
				cairo_line_to (_tmp66_, _tmp67_, _tmp69_);
			}
		}
	}
	_tmp70_ = ctx;
	cairo_stroke (_tmp70_);
	_tmp71_ = self->priv->fd;
	pango_font_description_set_absolute_size (_tmp71_, (gdouble) (9 * 1024));
	_tmp72_ = layout;
	_tmp73_ = self->priv->fd;
	pango_layout_set_font_description (_tmp72_, _tmp73_);
	idx = 1;
	{
		gdouble x_dash = 0.0;
		Gpxgraph_sizes_t _tmp74_ = {0};
		gdouble _tmp75_ = 0.0;
		gint _tmp76_ = 0;
		_tmp74_ = gs;
		_tmp75_ = _tmp74_.start_x;
		_tmp76_ = x_stepsize;
		x_dash = _tmp75_ + _tmp76_;
		{
			gboolean _tmp77_ = FALSE;
			_tmp77_ = TRUE;
			while (TRUE) {
				gdouble _tmp80_ = 0.0;
				Gpxgraph_sizes_t _tmp81_ = {0};
				gdouble _tmp82_ = 0.0;
				gint w = 0;
				gint h = 0;
				gdouble unit = 0.0;
				GpxGraph2ViewData* _tmp83_ = NULL;
				GeeArrayList* _tmp84_ = NULL;
				GpxGraph2ViewData* _tmp85_ = NULL;
				GeeArrayList* _tmp86_ = NULL;
				gint _tmp87_ = 0;
				gint _tmp88_ = 0;
				gint _tmp89_ = 0;
				gfloat _tmp90_ = 0.0F;
				gdouble _tmp91_ = 0.0;
				gpointer _tmp92_ = NULL;
				Gpx2DPoint* _tmp93_ = NULL;
				gdouble _tmp94_ = 0.0;
				gdouble _tmp95_ = 0.0;
				gchar* markup = NULL;
				const gchar* _tmp96_ = NULL;
				gdouble _tmp97_ = 0.0;
				gchar* _tmp98_ = NULL;
				PangoLayout* _tmp99_ = NULL;
				const gchar* _tmp100_ = NULL;
				PangoLayout* _tmp101_ = NULL;
				gint _tmp102_ = 0;
				gint _tmp103_ = 0;
				cairo_t* _tmp104_ = NULL;
				gdouble _tmp105_ = 0.0;
				gint _tmp106_ = 0;
				Gpxgraph_sizes_t _tmp107_ = {0};
				gdouble _tmp108_ = 0.0;
				cairo_t* _tmp109_ = NULL;
				PangoLayout* _tmp110_ = NULL;
				cairo_t* _tmp111_ = NULL;
				gint _tmp112_ = 0;
				if (!_tmp77_) {
					gdouble _tmp78_ = 0.0;
					gint _tmp79_ = 0;
					_tmp78_ = x_dash;
					_tmp79_ = x_stepsize;
					x_dash = _tmp78_ + _tmp79_;
				}
				_tmp77_ = FALSE;
				_tmp80_ = x_dash;
				_tmp81_ = gs;
				_tmp82_ = _tmp81_.end_x;
				if (!(_tmp80_ <= _tmp82_)) {
					break;
				}
				_tmp83_ = d;
				_tmp84_ = _tmp83_->points;
				_tmp85_ = d;
				_tmp86_ = _tmp85_->points;
				_tmp87_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp86_);
				_tmp88_ = _tmp87_;
				_tmp89_ = idx;
				_tmp90_ = steps;
				_tmp91_ = floor ((gdouble) (_tmp88_ * (_tmp89_ / _tmp90_)));
				_tmp92_ = gee_abstract_list_get ((GeeAbstractList*) _tmp84_, ((gint) _tmp91_) - 1);
				_tmp93_ = (Gpx2DPoint*) _tmp92_;
				_tmp94_ = (*_tmp93_).x;
				_tmp95_ = _tmp94_;
				_gpx_2d_point_free0 (_tmp93_);
				unit = _tmp95_;
				_tmp96_ = _ ("%.1f");
				_tmp97_ = unit;
				_tmp98_ = g_strdup_printf (_tmp96_, _tmp97_);
				markup = _tmp98_;
				_tmp99_ = layout;
				_tmp100_ = markup;
				pango_layout_set_markup (_tmp99_, _tmp100_, -1);
				_tmp101_ = layout;
				pango_layout_get_pixel_size (_tmp101_, &_tmp102_, &_tmp103_);
				w = _tmp102_;
				h = _tmp103_;
				_tmp104_ = ctx;
				_tmp105_ = x_dash;
				_tmp106_ = w;
				_tmp107_ = gs;
				_tmp108_ = _tmp107_.start_y;
				cairo_move_to (_tmp104_, _tmp105_ - (_tmp106_ / 2), _tmp108_ + 12);
				_tmp109_ = ctx;
				_tmp110_ = layout;
				pango_cairo_layout_path (_tmp109_, _tmp110_);
				_tmp111_ = ctx;
				cairo_fill (_tmp111_);
				_tmp112_ = idx;
				idx = _tmp112_ + 1;
				_g_free0 (markup);
			}
		}
	}
	_tmp113_ = gs;
	_tmp114_ = _tmp113_.graph_height;
	y_stepsize = _tmp114_ / 7;
	{
		GeeArrayList* _dy_list = NULL;
		GeeArrayList* _tmp115_ = NULL;
		GeeArrayList* _tmp116_ = NULL;
		gint _dy_size = 0;
		GeeArrayList* _tmp117_ = NULL;
		gint _tmp118_ = 0;
		gint _tmp119_ = 0;
		gint _dy_index = 0;
		_tmp115_ = self->_data;
		_tmp116_ = _g_object_ref0 (_tmp115_);
		_dy_list = _tmp116_;
		_tmp117_ = _dy_list;
		_tmp118_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp117_);
		_tmp119_ = _tmp118_;
		_dy_size = _tmp119_;
		_dy_index = -1;
		while (TRUE) {
			gint _tmp120_ = 0;
			gint _tmp121_ = 0;
			gint _tmp122_ = 0;
			GpxGraph2ViewData* dy = NULL;
			GeeArrayList* _tmp123_ = NULL;
			gint _tmp124_ = 0;
			gpointer _tmp125_ = NULL;
			cairo_t* _tmp126_ = NULL;
			GpxGraph2ViewData* _tmp127_ = NULL;
			GpxGraph2ViewDatastyle_t _tmp128_ = {0};
			GdkRGBA _tmp129_ = {0};
			gdouble at_x = 0.0;
			GpxGraph2ViewData* _tmp130_ = NULL;
			gint _tmp131_ = 0;
			cairo_t* _tmp142_ = NULL;
			gdouble _tmp143_ = 0.0;
			Gpxgraph_sizes_t _tmp144_ = {0};
			gdouble _tmp145_ = 0.0;
			cairo_t* _tmp146_ = NULL;
			gdouble _tmp147_ = 0.0;
			Gpxgraph_sizes_t _tmp148_ = {0};
			gdouble _tmp149_ = 0.0;
			gint _tmp150_ = 0;
			GpxGraph2ViewData* _tmp151_ = NULL;
			gint _tmp152_ = 0;
			gint stroke_dir = 0;
			cairo_t* _tmp168_ = NULL;
			_tmp120_ = _dy_index;
			_dy_index = _tmp120_ + 1;
			_tmp121_ = _dy_index;
			_tmp122_ = _dy_size;
			if (!(_tmp121_ < _tmp122_)) {
				break;
			}
			_tmp123_ = _dy_list;
			_tmp124_ = _dy_index;
			_tmp125_ = gee_abstract_list_get ((GeeAbstractList*) _tmp123_, _tmp124_);
			dy = (GpxGraph2ViewData*) _tmp125_;
			_tmp126_ = ctx;
			_tmp127_ = dy;
			_tmp128_ = _tmp127_->style;
			_tmp129_ = _tmp128_.color;
			gdk_cairo_set_source_rgba (_tmp126_, &_tmp129_);
			at_x = (gdouble) 0;
			_tmp130_ = dy;
			_tmp131_ = _tmp130_->axis_position;
			if (_tmp131_ > 0) {
				Gpxgraph_sizes_t _tmp132_ = {0};
				gdouble _tmp133_ = 0.0;
				GpxGraph2ViewData* _tmp134_ = NULL;
				gint _tmp135_ = 0;
				gint _tmp136_ = 0;
				_tmp132_ = gs;
				_tmp133_ = _tmp132_.end_x;
				_tmp134_ = dy;
				_tmp135_ = _tmp134_->axis_position;
				_tmp136_ = self->priv->AXIS_MARGIN;
				at_x = _tmp133_ + ((_tmp135_ - 1) * _tmp136_);
			} else {
				Gpxgraph_sizes_t _tmp137_ = {0};
				gdouble _tmp138_ = 0.0;
				GpxGraph2ViewData* _tmp139_ = NULL;
				gint _tmp140_ = 0;
				gint _tmp141_ = 0;
				_tmp137_ = gs;
				_tmp138_ = _tmp137_.start_x;
				_tmp139_ = dy;
				_tmp140_ = _tmp139_->axis_position;
				_tmp141_ = self->priv->AXIS_MARGIN;
				at_x = _tmp138_ + ((_tmp140_ + 1) * _tmp141_);
			}
			_tmp142_ = ctx;
			_tmp143_ = at_x;
			_tmp144_ = gs;
			_tmp145_ = _tmp144_.start_y;
			cairo_move_to (_tmp142_, _tmp143_, _tmp145_);
			_tmp146_ = ctx;
			_tmp147_ = at_x;
			_tmp148_ = gs;
			_tmp149_ = _tmp148_.end_y;
			cairo_line_to (_tmp146_, _tmp147_, _tmp149_);
			_tmp151_ = dy;
			_tmp152_ = _tmp151_->axis_position;
			if (_tmp152_ > 0) {
				_tmp150_ = 5;
			} else {
				_tmp150_ = -5;
			}
			stroke_dir = _tmp150_;
			{
				gdouble y_dash = 0.0;
				Gpxgraph_sizes_t _tmp153_ = {0};
				gdouble _tmp154_ = 0.0;
				_tmp153_ = gs;
				_tmp154_ = _tmp153_.start_y;
				y_dash = _tmp154_;
				{
					gboolean _tmp155_ = FALSE;
					_tmp155_ = TRUE;
					while (TRUE) {
						gdouble _tmp158_ = 0.0;
						Gpxgraph_sizes_t _tmp159_ = {0};
						gdouble _tmp160_ = 0.0;
						cairo_t* _tmp161_ = NULL;
						gdouble _tmp162_ = 0.0;
						gint _tmp163_ = 0;
						gdouble _tmp164_ = 0.0;
						cairo_t* _tmp165_ = NULL;
						gdouble _tmp166_ = 0.0;
						gdouble _tmp167_ = 0.0;
						if (!_tmp155_) {
							gdouble _tmp156_ = 0.0;
							gdouble _tmp157_ = 0.0;
							_tmp156_ = y_dash;
							_tmp157_ = y_stepsize;
							y_dash = _tmp156_ - _tmp157_;
						}
						_tmp155_ = FALSE;
						_tmp158_ = y_dash;
						_tmp159_ = gs;
						_tmp160_ = _tmp159_.end_y;
						if (!(_tmp158_ > _tmp160_)) {
							break;
						}
						_tmp161_ = ctx;
						_tmp162_ = at_x;
						_tmp163_ = stroke_dir;
						_tmp164_ = y_dash;
						cairo_move_to (_tmp161_, _tmp162_ + _tmp163_, _tmp164_);
						_tmp165_ = ctx;
						_tmp166_ = at_x;
						_tmp167_ = y_dash;
						cairo_line_to (_tmp165_, _tmp166_, _tmp167_);
					}
				}
			}
			_tmp168_ = ctx;
			cairo_stroke (_tmp168_);
			idx = 0;
			{
				gdouble y_dash = 0.0;
				Gpxgraph_sizes_t _tmp169_ = {0};
				gdouble _tmp170_ = 0.0;
				_tmp169_ = gs;
				_tmp170_ = _tmp169_.start_y;
				y_dash = _tmp170_;
				{
					gboolean _tmp171_ = FALSE;
					_tmp171_ = TRUE;
					while (TRUE) {
						gdouble _tmp174_ = 0.0;
						Gpxgraph_sizes_t _tmp175_ = {0};
						gdouble _tmp176_ = 0.0;
						gint w = 0;
						gint h = 0;
						gdouble unit = 0.0;
						GpxGraph2ViewData* _tmp177_ = NULL;
						Gpx2DPoint _tmp178_ = {0};
						gdouble _tmp179_ = 0.0;
						GpxGraph2ViewData* _tmp180_ = NULL;
						Gpx2DPoint _tmp181_ = {0};
						gdouble _tmp182_ = 0.0;
						GpxGraph2ViewData* _tmp183_ = NULL;
						Gpx2DPoint _tmp184_ = {0};
						gdouble _tmp185_ = 0.0;
						gint _tmp186_ = 0;
						gchar* markup = NULL;
						const gchar* _tmp187_ = NULL;
						gdouble _tmp188_ = 0.0;
						gchar* _tmp189_ = NULL;
						PangoLayout* _tmp190_ = NULL;
						const gchar* _tmp191_ = NULL;
						PangoLayout* _tmp192_ = NULL;
						gint _tmp193_ = 0;
						gint _tmp194_ = 0;
						GpxGraph2ViewData* _tmp195_ = NULL;
						gint _tmp196_ = 0;
						cairo_t* _tmp206_ = NULL;
						PangoLayout* _tmp207_ = NULL;
						cairo_t* _tmp208_ = NULL;
						gint _tmp209_ = 0;
						if (!_tmp171_) {
							gdouble _tmp172_ = 0.0;
							gdouble _tmp173_ = 0.0;
							_tmp172_ = y_dash;
							_tmp173_ = y_stepsize;
							y_dash = _tmp172_ - _tmp173_;
						}
						_tmp171_ = FALSE;
						_tmp174_ = y_dash;
						_tmp175_ = gs;
						_tmp176_ = _tmp175_.end_y;
						if (!(_tmp174_ > _tmp176_)) {
							break;
						}
						_tmp177_ = dy;
						_tmp178_ = _tmp177_->min;
						_tmp179_ = _tmp178_.y;
						_tmp180_ = dy;
						_tmp181_ = _tmp180_->max;
						_tmp182_ = _tmp181_.y;
						_tmp183_ = dy;
						_tmp184_ = _tmp183_->min;
						_tmp185_ = _tmp184_.y;
						_tmp186_ = idx;
						unit = _tmp179_ + ((_tmp182_ - _tmp185_) * (_tmp186_ / 7.0f));
						_tmp187_ = _ ("%.1f");
						_tmp188_ = unit;
						_tmp189_ = g_strdup_printf (_tmp187_, _tmp188_);
						markup = _tmp189_;
						_tmp190_ = layout;
						_tmp191_ = markup;
						pango_layout_set_markup (_tmp190_, _tmp191_, -1);
						_tmp192_ = layout;
						pango_layout_get_pixel_size (_tmp192_, &_tmp193_, &_tmp194_);
						w = _tmp193_;
						h = _tmp194_;
						_tmp195_ = dy;
						_tmp196_ = _tmp195_->axis_position;
						if (_tmp196_ > 0) {
							cairo_t* _tmp197_ = NULL;
							gdouble _tmp198_ = 0.0;
							gdouble _tmp199_ = 0.0;
							gint _tmp200_ = 0;
							_tmp197_ = ctx;
							_tmp198_ = at_x;
							_tmp199_ = y_dash;
							_tmp200_ = h;
							cairo_move_to (_tmp197_, _tmp198_ + 8, _tmp199_ - (_tmp200_ / 2));
						} else {
							cairo_t* _tmp201_ = NULL;
							gdouble _tmp202_ = 0.0;
							gint _tmp203_ = 0;
							gdouble _tmp204_ = 0.0;
							gint _tmp205_ = 0;
							_tmp201_ = ctx;
							_tmp202_ = at_x;
							_tmp203_ = w;
							_tmp204_ = y_dash;
							_tmp205_ = h;
							cairo_move_to (_tmp201_, (_tmp202_ - _tmp203_) - 8, _tmp204_ - (_tmp205_ / 2));
						}
						_tmp206_ = ctx;
						_tmp207_ = layout;
						pango_cairo_layout_path (_tmp206_, _tmp207_);
						_tmp208_ = ctx;
						cairo_fill (_tmp208_);
						_tmp209_ = idx;
						idx = _tmp209_ + 1;
						_g_free0 (markup);
					}
				}
			}
			_gpx_graph2_view_data_unref0 (dy);
		}
		_g_object_unref0 (_dy_list);
	}
	_tmp210_ = ctx;
	cairo_set_source_rgba (_tmp210_, (gdouble) 0, (gdouble) 0, (gdouble) 0, 0.5);
	{
		gdouble y_dash = 0.0;
		Gpxgraph_sizes_t _tmp211_ = {0};
		gdouble _tmp212_ = 0.0;
		gdouble _tmp213_ = 0.0;
		_tmp211_ = gs;
		_tmp212_ = _tmp211_.start_y;
		_tmp213_ = y_stepsize;
		y_dash = _tmp212_ - _tmp213_;
		{
			gboolean _tmp214_ = FALSE;
			_tmp214_ = TRUE;
			while (TRUE) {
				gdouble _tmp217_ = 0.0;
				Gpxgraph_sizes_t _tmp218_ = {0};
				gdouble _tmp219_ = 0.0;
				cairo_t* _tmp220_ = NULL;
				Gpxgraph_sizes_t _tmp221_ = {0};
				gdouble _tmp222_ = 0.0;
				gdouble _tmp223_ = 0.0;
				cairo_t* _tmp224_ = NULL;
				Gpxgraph_sizes_t _tmp225_ = {0};
				gdouble _tmp226_ = 0.0;
				gdouble _tmp227_ = 0.0;
				if (!_tmp214_) {
					gdouble _tmp215_ = 0.0;
					gdouble _tmp216_ = 0.0;
					_tmp215_ = y_dash;
					_tmp216_ = y_stepsize;
					y_dash = _tmp215_ - _tmp216_;
				}
				_tmp214_ = FALSE;
				_tmp217_ = y_dash;
				_tmp218_ = gs;
				_tmp219_ = _tmp218_.end_y;
				if (!(_tmp217_ > _tmp219_)) {
					break;
				}
				_tmp220_ = ctx;
				_tmp221_ = gs;
				_tmp222_ = _tmp221_.start_x;
				_tmp223_ = y_dash;
				cairo_move_to (_tmp220_, _tmp222_, _tmp223_);
				_tmp224_ = ctx;
				_tmp225_ = gs;
				_tmp226_ = _tmp225_.end_x;
				_tmp227_ = y_dash;
				cairo_line_to (_tmp224_, _tmp226_, _tmp227_);
			}
		}
	}
	_tmp228_ = ctx;
	cairo_stroke (_tmp228_);
	_gpx_graph2_view_data_unref0 (d);
}


static gboolean gpx_graph2_view_expose_cb (GpxGraph2View* self, cairo_t* ctx) {
	gboolean result = FALSE;
	cairo_surface_t* _tmp0_ = NULL;
	GtkAllocation alloc = {0};
	GtkAllocation _tmp1_ = {0};
	cairo_t* _tmp2_ = NULL;
	cairo_surface_t* _tmp3_ = NULL;
	cairo_t* _tmp4_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (ctx != NULL, FALSE);
	_tmp0_ = self->priv->surf;
	if (_tmp0_ == NULL) {
		gpx_graph2_view_update_surface (self, (GtkWidget*) self);
	}
	gtk_widget_get_allocation ((GtkWidget*) self, &_tmp1_);
	alloc = _tmp1_;
	_tmp2_ = ctx;
	_tmp3_ = self->priv->surf;
	cairo_set_source_surface (_tmp2_, _tmp3_, (gdouble) 0, (gdouble) 0);
	_tmp4_ = ctx;
	cairo_paint (_tmp4_);
	result = FALSE;
	return result;
}


static GdkRGBA* _gdk_rgba_dup (GdkRGBA* self) {
	GdkRGBA* dup;
	dup = g_new0 (GdkRGBA, 1);
	memcpy (dup, self, sizeof (GdkRGBA));
	return dup;
}


static gpointer __gdk_rgba_dup0 (gpointer self) {
	return self ? _gdk_rgba_dup (self) : NULL;
}


GpxGraph2ViewData* gpx_graph2_view_data_construct (GType object_type, GeeArrayList* data, gint axis_position, GdkRGBA* color, GdkRGBA* fill) {
	GpxGraph2ViewData* self = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GdkRGBA _tmp3_ = {0};
	GdkRGBA* _tmp4_ = NULL;
	GdkRGBA* _tmp5_ = NULL;
	GdkRGBA* _tmp6_ = NULL;
	g_return_val_if_fail (data != NULL, NULL);
	g_return_val_if_fail (color != NULL, NULL);
	self = (GpxGraph2ViewData*) g_type_create_instance (object_type);
	_tmp0_ = data;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->points);
	self->points = _tmp1_;
	_tmp2_ = axis_position;
	self->axis_position = _tmp2_;
	_tmp3_ = *color;
	self->style.color = _tmp3_;
	_tmp4_ = fill;
	_tmp5_ = __gdk_rgba_dup0 (_tmp4_);
	_g_free0 (self->style.fill);
	self->style.fill = _tmp5_;
	_tmp6_ = fill;
	if (_tmp6_ != NULL) {
		FILE* _tmp7_ = NULL;
		_tmp7_ = stdout;
		fprintf (_tmp7_, "FILLEDDDDDDDd");
	}
	gpx_graph2_view_data_find_min_max (self);
	return self;
}


GpxGraph2ViewData* gpx_graph2_view_data_new (GeeArrayList* data, gint axis_position, GdkRGBA* color, GdkRGBA* fill) {
	return gpx_graph2_view_data_construct (GPX_GRAPH2_VIEW_TYPE_DATA, data, axis_position, color, fill);
}


static gdouble gpx_graph2_view_data_round_to_multiple (GpxGraph2ViewData* self, gdouble num_to_round, gint multiple, gboolean negative) {
	gdouble result = 0.0;
	gint num = 0;
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gboolean _tmp2_ = FALSE;
	gint _tmp5_ = 0;
	gint remainder = 0;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	gint _tmp11_ = 0;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = num_to_round;
	_tmp1_ = ceil (_tmp0_);
	num = (gint) _tmp1_;
	_tmp2_ = negative;
	if (_tmp2_) {
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		_tmp3_ = num;
		_tmp4_ = multiple;
		num = _tmp3_ - _tmp4_;
	}
	_tmp5_ = multiple;
	if (_tmp5_ == 0) {
		gdouble _tmp6_ = 0.0;
		_tmp6_ = num_to_round;
		result = _tmp6_;
		return result;
	}
	_tmp7_ = num;
	_tmp8_ = multiple;
	remainder = _tmp7_ % _tmp8_;
	_tmp9_ = remainder;
	if (_tmp9_ == 0) {
		gint _tmp10_ = 0;
		_tmp10_ = num;
		result = (gdouble) _tmp10_;
		return result;
	}
	_tmp11_ = num;
	_tmp12_ = multiple;
	_tmp13_ = remainder;
	result = (((gdouble) _tmp11_) + _tmp12_) - _tmp13_;
	return result;
}


static void gpx_graph2_view_data_find_min_max (GpxGraph2ViewData* self) {
	Gpx2DPoint min = {0};
	Gpx2DPoint _tmp0_ = {0};
	Gpx2DPoint max = {0};
	Gpx2DPoint _tmp1_ = {0};
	Gpx2DPoint _tmp51_ = {0};
	gdouble _tmp52_ = 0.0;
	gdouble _tmp53_ = 0.0;
	Gpx2DPoint _tmp54_ = {0};
	gdouble _tmp55_ = 0.0;
	gdouble _tmp56_ = 0.0;
	Gpx2DPoint _tmp57_ = {0};
	Gpx2DPoint _tmp58_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_.x = 10000.0;
	_tmp0_.y = 10000.0;
	min = _tmp0_;
	_tmp1_.x = -10000.0;
	_tmp1_.y = -10000.0;
	max = _tmp1_;
	{
		GeeArrayList* _p_list = NULL;
		GeeArrayList* _tmp2_ = NULL;
		GeeArrayList* _tmp3_ = NULL;
		gint _p_size = 0;
		GeeArrayList* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		gint _p_index = 0;
		_tmp2_ = self->points;
		_tmp3_ = _g_object_ref0 (_tmp2_);
		_p_list = _tmp3_;
		_tmp4_ = _p_list;
		_tmp5_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp4_);
		_tmp6_ = _tmp5_;
		_p_size = _tmp6_;
		_p_index = -1;
		while (TRUE) {
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
			gint _tmp9_ = 0;
			Gpx2DPoint p = {0};
			GeeArrayList* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			gpointer _tmp12_ = NULL;
			Gpx2DPoint* _tmp13_ = NULL;
			Gpx2DPoint _tmp14_ = {0};
			gdouble _tmp15_ = 0.0;
			Gpx2DPoint _tmp16_ = {0};
			gdouble _tmp17_ = 0.0;
			Gpx2DPoint _tmp18_ = {0};
			gdouble _tmp19_ = 0.0;
			gdouble _tmp24_ = 0.0;
			Gpx2DPoint _tmp25_ = {0};
			gdouble _tmp26_ = 0.0;
			Gpx2DPoint _tmp27_ = {0};
			gdouble _tmp28_ = 0.0;
			gdouble _tmp33_ = 0.0;
			Gpx2DPoint _tmp34_ = {0};
			gdouble _tmp35_ = 0.0;
			Gpx2DPoint _tmp36_ = {0};
			gdouble _tmp37_ = 0.0;
			gdouble _tmp42_ = 0.0;
			Gpx2DPoint _tmp43_ = {0};
			gdouble _tmp44_ = 0.0;
			Gpx2DPoint _tmp45_ = {0};
			gdouble _tmp46_ = 0.0;
			_tmp7_ = _p_index;
			_p_index = _tmp7_ + 1;
			_tmp8_ = _p_index;
			_tmp9_ = _p_size;
			if (!(_tmp8_ < _tmp9_)) {
				break;
			}
			_tmp10_ = _p_list;
			_tmp11_ = _p_index;
			_tmp12_ = gee_abstract_list_get ((GeeAbstractList*) _tmp10_, _tmp11_);
			_tmp13_ = (Gpx2DPoint*) _tmp12_;
			_tmp14_ = *_tmp13_;
			_gpx_2d_point_free0 (_tmp13_);
			p = _tmp14_;
			_tmp16_ = p;
			_tmp17_ = _tmp16_.x;
			_tmp18_ = min;
			_tmp19_ = _tmp18_.x;
			if (_tmp17_ < _tmp19_) {
				Gpx2DPoint _tmp20_ = {0};
				gdouble _tmp21_ = 0.0;
				_tmp20_ = p;
				_tmp21_ = _tmp20_.x;
				_tmp15_ = _tmp21_;
			} else {
				Gpx2DPoint _tmp22_ = {0};
				gdouble _tmp23_ = 0.0;
				_tmp22_ = min;
				_tmp23_ = _tmp22_.x;
				_tmp15_ = _tmp23_;
			}
			min.x = _tmp15_;
			_tmp25_ = p;
			_tmp26_ = _tmp25_.y;
			_tmp27_ = min;
			_tmp28_ = _tmp27_.y;
			if (_tmp26_ < _tmp28_) {
				Gpx2DPoint _tmp29_ = {0};
				gdouble _tmp30_ = 0.0;
				_tmp29_ = p;
				_tmp30_ = _tmp29_.y;
				_tmp24_ = _tmp30_;
			} else {
				Gpx2DPoint _tmp31_ = {0};
				gdouble _tmp32_ = 0.0;
				_tmp31_ = min;
				_tmp32_ = _tmp31_.y;
				_tmp24_ = _tmp32_;
			}
			min.y = _tmp24_;
			_tmp34_ = p;
			_tmp35_ = _tmp34_.x;
			_tmp36_ = max;
			_tmp37_ = _tmp36_.x;
			if (_tmp35_ > _tmp37_) {
				Gpx2DPoint _tmp38_ = {0};
				gdouble _tmp39_ = 0.0;
				_tmp38_ = p;
				_tmp39_ = _tmp38_.x;
				_tmp33_ = _tmp39_;
			} else {
				Gpx2DPoint _tmp40_ = {0};
				gdouble _tmp41_ = 0.0;
				_tmp40_ = max;
				_tmp41_ = _tmp40_.x;
				_tmp33_ = _tmp41_;
			}
			max.x = _tmp33_;
			_tmp43_ = p;
			_tmp44_ = _tmp43_.y;
			_tmp45_ = max;
			_tmp46_ = _tmp45_.y;
			if (_tmp44_ > _tmp46_) {
				Gpx2DPoint _tmp47_ = {0};
				gdouble _tmp48_ = 0.0;
				_tmp47_ = p;
				_tmp48_ = _tmp47_.y;
				_tmp42_ = _tmp48_;
			} else {
				Gpx2DPoint _tmp49_ = {0};
				gdouble _tmp50_ = 0.0;
				_tmp49_ = max;
				_tmp50_ = _tmp49_.y;
				_tmp42_ = _tmp50_;
			}
			max.y = _tmp42_;
		}
		_g_object_unref0 (_p_list);
	}
	_tmp51_ = min;
	_tmp52_ = _tmp51_.y;
	_tmp53_ = gpx_graph2_view_data_round_to_multiple (self, _tmp52_, 10, TRUE);
	min.y = _tmp53_;
	_tmp54_ = max;
	_tmp55_ = _tmp54_.y;
	_tmp56_ = gpx_graph2_view_data_round_to_multiple (self, _tmp55_, 10, FALSE);
	max.y = _tmp56_;
	_tmp57_ = min;
	self->min = _tmp57_;
	_tmp58_ = max;
	self->max = _tmp58_;
}


void gpx_graph2_view_data_style_t_copy (const GpxGraph2ViewDatastyle_t* self, GpxGraph2ViewDatastyle_t* dest) {
	GdkRGBA _tmp0_ = {0};
	GdkRGBA* _tmp1_ = NULL;
	GdkRGBA* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	_tmp0_ = (*self).color;
	(*dest).color = _tmp0_;
	_tmp1_ = (*self).fill;
	_tmp2_ = __gdk_rgba_dup0 (_tmp1_);
	_g_free0 ((*dest).fill);
	(*dest).fill = _tmp2_;
	_tmp3_ = (*self).line_width;
	(*dest).line_width = _tmp3_;
}


void gpx_graph2_view_data_style_t_destroy (GpxGraph2ViewDatastyle_t* self) {
	_g_free0 ((*self).fill);
}


GpxGraph2ViewDatastyle_t* gpx_graph2_view_data_style_t_dup (const GpxGraph2ViewDatastyle_t* self) {
	GpxGraph2ViewDatastyle_t* dup;
	dup = g_new0 (GpxGraph2ViewDatastyle_t, 1);
	gpx_graph2_view_data_style_t_copy (self, dup);
	return dup;
}


void gpx_graph2_view_data_style_t_free (GpxGraph2ViewDatastyle_t* self) {
	gpx_graph2_view_data_style_t_destroy (self);
	g_free (self);
}


GType gpx_graph2_view_data_style_t_get_type (void) {
	static volatile gsize gpx_graph2_view_data_style_t_type_id__volatile = 0;
	if (g_once_init_enter (&gpx_graph2_view_data_style_t_type_id__volatile)) {
		GType gpx_graph2_view_data_style_t_type_id;
		gpx_graph2_view_data_style_t_type_id = g_boxed_type_register_static ("GpxGraph2ViewDatastyle_t", (GBoxedCopyFunc) gpx_graph2_view_data_style_t_dup, (GBoxedFreeFunc) gpx_graph2_view_data_style_t_free);
		g_once_init_leave (&gpx_graph2_view_data_style_t_type_id__volatile, gpx_graph2_view_data_style_t_type_id);
	}
	return gpx_graph2_view_data_style_t_type_id__volatile;
}


static void gpx_graph2_view_value_data_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void gpx_graph2_view_value_data_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		gpx_graph2_view_data_unref (value->data[0].v_pointer);
	}
}


static void gpx_graph2_view_value_data_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gpx_graph2_view_data_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer gpx_graph2_view_value_data_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* gpx_graph2_view_value_data_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GpxGraph2ViewData* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gpx_graph2_view_data_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* gpx_graph2_view_value_data_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GpxGraph2ViewData** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gpx_graph2_view_data_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* gpx_graph2_view_param_spec_data (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	GpxGraph2ViewParamSpecData* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GPX_GRAPH2_VIEW_TYPE_DATA), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer gpx_graph2_view_value_get_data (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GPX_GRAPH2_VIEW_TYPE_DATA), NULL);
	return value->data[0].v_pointer;
}


void gpx_graph2_view_value_set_data (GValue* value, gpointer v_object) {
	GpxGraph2ViewData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GPX_GRAPH2_VIEW_TYPE_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GPX_GRAPH2_VIEW_TYPE_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gpx_graph2_view_data_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gpx_graph2_view_data_unref (old);
	}
}


void gpx_graph2_view_value_take_data (GValue* value, gpointer v_object) {
	GpxGraph2ViewData* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GPX_GRAPH2_VIEW_TYPE_DATA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GPX_GRAPH2_VIEW_TYPE_DATA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gpx_graph2_view_data_unref (old);
	}
}


static void gpx_graph2_view_data_class_init (GpxGraph2ViewDataClass * klass) {
	gpx_graph2_view_data_parent_class = g_type_class_peek_parent (klass);
	((GpxGraph2ViewDataClass *) klass)->finalize = gpx_graph2_view_data_finalize;
}


static void gpx_graph2_view_data_instance_init (GpxGraph2ViewData * self) {
	GeeArrayList* _tmp0_ = NULL;
	GdkRGBA _tmp1_ = {0};
	GpxGraph2ViewDatastyle_t _tmp2_ = {0};
	_tmp0_ = gee_array_list_new (GPX_TYPE_2D_POINT, (GBoxedCopyFunc) gpx_2d_point_dup, gpx_2d_point_free, NULL, NULL, NULL);
	self->points = _tmp0_;
	memset (&self->max, 0, sizeof (Gpx2DPoint));
	memset (&self->min, 0, sizeof (Gpx2DPoint));
	self->axis_position = -1;
	_tmp1_.red = (gdouble) 0;
	_tmp1_.green = (gdouble) 0;
	_tmp1_.blue = (gdouble) 0;
	_tmp1_.alpha = (gdouble) 1;
	memset (&_tmp2_, 0, sizeof (GpxGraph2ViewDatastyle_t));
	_tmp2_.color = _tmp1_;
	_g_free0 (_tmp2_.fill);
	_tmp2_.fill = NULL;
	_tmp2_.line_width = (gdouble) 1;
	self->style = _tmp2_;
	self->ref_count = 1;
}


static void gpx_graph2_view_data_finalize (GpxGraph2ViewData* obj) {
	GpxGraph2ViewData * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GPX_GRAPH2_VIEW_TYPE_DATA, GpxGraph2ViewData);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->points);
	gpx_graph2_view_data_style_t_destroy (&self->style);
}


GType gpx_graph2_view_data_get_type (void) {
	static volatile gsize gpx_graph2_view_data_type_id__volatile = 0;
	if (g_once_init_enter (&gpx_graph2_view_data_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { gpx_graph2_view_value_data_init, gpx_graph2_view_value_data_free_value, gpx_graph2_view_value_data_copy_value, gpx_graph2_view_value_data_peek_pointer, "p", gpx_graph2_view_value_data_collect_value, "p", gpx_graph2_view_value_data_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GpxGraph2ViewDataClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gpx_graph2_view_data_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GpxGraph2ViewData), 0, (GInstanceInitFunc) gpx_graph2_view_data_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType gpx_graph2_view_data_type_id;
		gpx_graph2_view_data_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GpxGraph2ViewData", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&gpx_graph2_view_data_type_id__volatile, gpx_graph2_view_data_type_id);
	}
	return gpx_graph2_view_data_type_id__volatile;
}


gpointer gpx_graph2_view_data_ref (gpointer instance) {
	GpxGraph2ViewData* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void gpx_graph2_view_data_unref (gpointer instance) {
	GpxGraph2ViewData* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GPX_GRAPH2_VIEW_DATA_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void gpx_graph2_view_class_init (GpxGraph2ViewClass * klass) {
	gpx_graph2_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GpxGraph2ViewPrivate));
	G_OBJECT_CLASS (klass)->finalize = gpx_graph2_view_finalize;
}


static void gpx_graph2_view_instance_init (GpxGraph2View * self) {
	GeeArrayList* _tmp0_ = NULL;
	self->priv = GPX_GRAPH2_VIEW_GET_PRIVATE (self);
	self->priv->fd = NULL;
	self->priv->surf = NULL;
	self->priv->OFFSET_LEFT = 150.5;
	self->priv->OFFSET_BOTTOM = 30.5;
	self->priv->OFFSET_TOP = 30.5;
	self->priv->OFFSET_RIGHT = 50.5;
	self->priv->highlight = -1;
	self->priv->AXIS_MARGIN = 50;
	_tmp0_ = gee_array_list_new (GPX_GRAPH2_VIEW_TYPE_DATA, (GBoxedCopyFunc) gpx_graph2_view_data_ref, gpx_graph2_view_data_unref, NULL, NULL, NULL);
	self->_data = _tmp0_;
}


static void gpx_graph2_view_finalize (GObject* obj) {
	GpxGraph2View * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GPX_TYPE_GRAPH2_VIEW, GpxGraph2View);
	__vala_PangoFontDescription_free0 (self->priv->fd);
	_cairo_surface_destroy0 (self->priv->surf);
	_g_object_unref0 (self->_data);
	G_OBJECT_CLASS (gpx_graph2_view_parent_class)->finalize (obj);
}


GType gpx_graph2_view_get_type (void) {
	static volatile gsize gpx_graph2_view_type_id__volatile = 0;
	if (g_once_init_enter (&gpx_graph2_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GpxGraph2ViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gpx_graph2_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GpxGraph2View), 0, (GInstanceInitFunc) gpx_graph2_view_instance_init, NULL };
		GType gpx_graph2_view_type_id;
		gpx_graph2_view_type_id = g_type_register_static (gtk_event_box_get_type (), "GpxGraph2View", &g_define_type_info, 0);
		g_once_init_leave (&gpx_graph2_view_type_id__volatile, gpx_graph2_view_type_id);
	}
	return gpx_graph2_view_type_id__volatile;
}


static gpointer _gpx_point_ref0 (gpointer self) {
	return self ? gpx_point_ref (self) : NULL;
}


void gpx_graph_set_track (GpxGraph* self, GpxTrack* track) {
	GpxTrack* _tmp0_ = NULL;
	GpxTrack* _tmp1_ = NULL;
	GeeArrayList* data_elevation = NULL;
	GeeArrayList* _tmp2_ = NULL;
	GeeArrayList* data_heart = NULL;
	GeeArrayList* _tmp3_ = NULL;
	GeeArrayList* data_speed = NULL;
	GeeArrayList* _tmp4_ = NULL;
	GpxTrack* _tmp5_ = NULL;
	GList* _tmp6_ = NULL;
	GpxGraph2View* _tmp27_ = NULL;
	GeeArrayList* _tmp28_ = NULL;
	GdkRGBA _tmp29_ = {0};
	GdkRGBA _tmp30_ = {0};
	GpxGraph2View* _tmp31_ = NULL;
	GeeArrayList* _tmp32_ = NULL;
	GdkRGBA _tmp33_ = {0};
	GpxGraph2View* _tmp34_ = NULL;
	GeeArrayList* _tmp35_ = NULL;
	GdkRGBA _tmp36_ = {0};
	GpxGraph2View* _tmp37_ = NULL;
	gboolean _tmp38_ = FALSE;
	GpxTrack* _tmp39_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = track;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->track);
	self->track = _tmp1_;
	_tmp2_ = gee_array_list_new (GPX_TYPE_2D_POINT, (GBoxedCopyFunc) gpx_2d_point_dup, gpx_2d_point_free, NULL, NULL, NULL);
	data_elevation = _tmp2_;
	_tmp3_ = gee_array_list_new (GPX_TYPE_2D_POINT, (GBoxedCopyFunc) gpx_2d_point_dup, gpx_2d_point_free, NULL, NULL, NULL);
	data_heart = _tmp3_;
	_tmp4_ = gee_array_list_new (GPX_TYPE_2D_POINT, (GBoxedCopyFunc) gpx_2d_point_dup, gpx_2d_point_free, NULL, NULL, NULL);
	data_speed = _tmp4_;
	_tmp5_ = track;
	_tmp6_ = _tmp5_->points;
	{
		GList* p_collection = NULL;
		GList* p_it = NULL;
		p_collection = _tmp6_;
		for (p_it = p_collection; p_it != NULL; p_it = p_it->next) {
			GpxPoint* _tmp7_ = NULL;
			GpxPoint* p = NULL;
			_tmp7_ = _gpx_point_ref0 ((GpxPoint*) p_it->data);
			p = _tmp7_;
			{
				GeeArrayList* _tmp8_ = NULL;
				GpxPoint* _tmp9_ = NULL;
				gdouble _tmp10_ = 0.0;
				GpxPoint* _tmp11_ = NULL;
				gdouble _tmp12_ = 0.0;
				Gpx2DPoint _tmp13_ = {0};
				GeeArrayList* _tmp14_ = NULL;
				GpxPoint* _tmp15_ = NULL;
				gdouble _tmp16_ = 0.0;
				GpxPoint* _tmp17_ = NULL;
				GpxHeartRateMonitorPoint _tmp18_ = {0};
				gint _tmp19_ = 0;
				Gpx2DPoint _tmp20_ = {0};
				GeeArrayList* _tmp21_ = NULL;
				GpxPoint* _tmp22_ = NULL;
				gdouble _tmp23_ = 0.0;
				GpxPoint* _tmp24_ = NULL;
				gdouble _tmp25_ = 0.0;
				Gpx2DPoint _tmp26_ = {0};
				_tmp8_ = data_elevation;
				_tmp9_ = p;
				_tmp10_ = _tmp9_->distance;
				_tmp11_ = p;
				_tmp12_ = _tmp11_->elevation;
				_tmp13_.x = _tmp10_;
				_tmp13_.y = _tmp12_;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp8_, &_tmp13_);
				_tmp14_ = data_heart;
				_tmp15_ = p;
				_tmp16_ = _tmp15_->distance;
				_tmp17_ = p;
				_tmp18_ = _tmp17_->tpe;
				_tmp19_ = _tmp18_.heartrate;
				_tmp20_.x = _tmp16_;
				_tmp20_.y = (gdouble) _tmp19_;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp14_, &_tmp20_);
				_tmp21_ = data_speed;
				_tmp22_ = p;
				_tmp23_ = _tmp22_->distance;
				_tmp24_ = p;
				_tmp25_ = _tmp24_->speed;
				_tmp26_.x = _tmp23_;
				_tmp26_.y = _tmp25_;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp21_, &_tmp26_);
				_gpx_point_unref0 (p);
			}
		}
	}
	_tmp27_ = self->priv->view;
	_tmp28_ = data_elevation;
	_tmp29_.red = 0.2;
	_tmp29_.green = 0.0;
	_tmp29_.blue = 0.7;
	_tmp29_.alpha = (gdouble) 1;
	_tmp30_.red = 0.2;
	_tmp30_.green = 0.0;
	_tmp30_.blue = 0.7;
	_tmp30_.alpha = 0.4;
	gpx_graph2_view_add_data (_tmp27_, _tmp28_, 1, &_tmp29_, &_tmp30_);
	_tmp31_ = self->priv->view;
	_tmp32_ = data_heart;
	_tmp33_.red = (gdouble) 1;
	_tmp33_.green = 0.0;
	_tmp33_.blue = 0.0;
	_tmp33_.alpha = (gdouble) 1;
	gpx_graph2_view_add_data (_tmp31_, _tmp32_, -2, &_tmp33_, NULL);
	_tmp34_ = self->priv->view;
	_tmp35_ = data_speed;
	_tmp36_.red = 0.1;
	_tmp36_.green = 0.7;
	_tmp36_.blue = 0.2;
	_tmp36_.alpha = (gdouble) 1;
	gpx_graph2_view_add_data (_tmp34_, _tmp35_, -1, &_tmp36_, NULL);
	_tmp37_ = self->priv->view;
	gpx_graph2_view_plot (_tmp37_);
	_tmp39_ = self->track;
	if (_tmp39_ != NULL) {
		GpxTrack* _tmp40_ = NULL;
		GList* _tmp41_ = NULL;
		_tmp40_ = self->track;
		_tmp41_ = _tmp40_->points;
		_tmp38_ = _tmp41_ != NULL;
	} else {
		_tmp38_ = FALSE;
	}
	if (_tmp38_) {
		GpxTrack* _tmp42_ = NULL;
		GpxTrack* _tmp43_ = NULL;
		GList* _tmp44_ = NULL;
		GList* _tmp45_ = NULL;
		gconstpointer _tmp46_ = NULL;
		GpxTrack* _tmp47_ = NULL;
		GList* _tmp48_ = NULL;
		GList* _tmp49_ = NULL;
		gconstpointer _tmp50_ = NULL;
		_tmp42_ = self->track;
		_tmp43_ = self->track;
		_tmp44_ = _tmp43_->points;
		_tmp45_ = g_list_first (_tmp44_);
		_tmp46_ = _tmp45_->data;
		_tmp47_ = self->track;
		_tmp48_ = _tmp47_->points;
		_tmp49_ = g_list_last (_tmp48_);
		_tmp50_ = _tmp49_->data;
		g_signal_emit_by_name (self, "selection-changed", _tmp42_, (GpxPoint*) _tmp46_, (GpxPoint*) _tmp50_);
	} else {
		GpxTrack* _tmp51_ = NULL;
		_tmp51_ = self->track;
		g_signal_emit_by_name (self, "selection-changed", _tmp51_, NULL, NULL);
	}
	_g_object_unref0 (data_speed);
	_g_object_unref0 (data_heart);
	_g_object_unref0 (data_elevation);
}


void gpx_graph_add_graph_to_container (GpxGraph* self, GtkContainer* container) {
	GtkContainer* _tmp0_ = NULL;
	GpxGraph2View* _tmp1_ = NULL;
	GpxGraph2View* _tmp2_ = NULL;
	GtkContainer* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (container != NULL);
	_tmp0_ = container;
	_tmp1_ = self->priv->view;
	gtk_container_add (_tmp0_, (GtkWidget*) _tmp1_);
	_tmp2_ = self->priv->view;
	gtk_widget_show ((GtkWidget*) _tmp2_);
	_tmp3_ = container;
	gtk_widget_show_all ((GtkWidget*) _tmp3_);
}


/** 
 * @param p A Gpx.Point we want to highlight.
 * pass null to unhighlight.
 */
void gpx_graph_highlight_point (GpxGraph* self, GpxPoint* p) {
	time_t _tmp0_ = 0;
	GpxPoint* _tmp1_ = NULL;
	time_t pt = 0;
	g_return_if_fail (self != NULL);
	_tmp1_ = p;
	if (_tmp1_ == NULL) {
		_tmp0_ = (time_t) 0;
	} else {
		GpxPoint* _tmp2_ = NULL;
		time_t _tmp3_ = 0;
		_tmp2_ = p;
		_tmp3_ = gpx_point_get_time (_tmp2_);
		_tmp0_ = _tmp3_;
	}
	pt = _tmp0_;
	gpx_graph_set_highlight (self, pt);
}


void gpx_graph_set_highlight (GpxGraph* self, time_t highlight) {
	g_return_if_fail (self != NULL);
}


void gpx_graph_hide_info (GpxGraph* self) {
	g_return_if_fail (self != NULL);
}


void gpx_graph_show_info (GpxGraph* self, GpxPoint* cur_point) {
	g_return_if_fail (self != NULL);
}


GpxGraph* gpx_graph_construct (GType object_type) {
	GpxGraph* self = NULL;
	self = (GpxGraph*) g_type_create_instance (object_type);
	return self;
}


GpxGraph* gpx_graph_new (void) {
	return gpx_graph_construct (GPX_TYPE_GRAPH);
}


gint gpx_graph_get_smooth_factor (GpxGraph* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_smooth_factor;
	result = _tmp0_;
	return result;
}


void gpx_graph_set_smooth_factor (GpxGraph* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_smooth_factor = _tmp0_;
}


gboolean gpx_graph_get_show_points (GpxGraph* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_show_points;
	result = _tmp0_;
	return result;
}


void gpx_graph_set_show_points (GpxGraph* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_show_points = _tmp0_;
}


static void g_cclosure_user_marshal_VOID__OBJECT_GPX_POINT_GPX_POINT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__OBJECT_GPX_POINT_GPX_POINT) (gpointer data1, gpointer arg_1, gpointer arg_2, gpointer arg_3, gpointer data2);
	register GMarshalFunc_VOID__OBJECT_GPX_POINT_GPX_POINT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 4);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__OBJECT_GPX_POINT_GPX_POINT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_object (param_values + 1), gpx_value_get_point (param_values + 2), gpx_value_get_point (param_values + 3), data2);
}


static void gpx_value_graph_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void gpx_value_graph_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		gpx_graph_unref (value->data[0].v_pointer);
	}
}


static void gpx_value_graph_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = gpx_graph_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer gpx_value_graph_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* gpx_value_graph_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		GpxGraph* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = gpx_graph_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* gpx_value_graph_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	GpxGraph** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = gpx_graph_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* gpx_param_spec_graph (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	GpxParamSpecGraph* spec;
	g_return_val_if_fail (g_type_is_a (object_type, GPX_TYPE_GRAPH), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer gpx_value_get_graph (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GPX_TYPE_GRAPH), NULL);
	return value->data[0].v_pointer;
}


void gpx_value_set_graph (GValue* value, gpointer v_object) {
	GpxGraph* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GPX_TYPE_GRAPH));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GPX_TYPE_GRAPH));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		gpx_graph_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gpx_graph_unref (old);
	}
}


void gpx_value_take_graph (GValue* value, gpointer v_object) {
	GpxGraph* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, GPX_TYPE_GRAPH));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, GPX_TYPE_GRAPH));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		gpx_graph_unref (old);
	}
}


static void gpx_graph_class_init (GpxGraphClass * klass) {
	gpx_graph_parent_class = g_type_class_peek_parent (klass);
	((GpxGraphClass *) klass)->finalize = gpx_graph_finalize;
	g_type_class_add_private (klass, sizeof (GpxGraphPrivate));
	g_signal_new ("selection_changed", GPX_TYPE_GRAPH, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__OBJECT_GPX_POINT_GPX_POINT, G_TYPE_NONE, 3, GPX_TYPE_TRACK, GPX_TYPE_POINT, GPX_TYPE_POINT);
}


static void gpx_graph_instance_init (GpxGraph * self) {
	GpxGraph2View* _tmp0_ = NULL;
	self->priv = GPX_GRAPH_GET_PRIVATE (self);
	self->track = NULL;
	self->priv->_smooth_factor = 1;
	self->priv->_show_points = TRUE;
	_tmp0_ = gpx_graph2_view_new ();
	g_object_ref_sink (_tmp0_);
	self->priv->view = _tmp0_;
	self->ref_count = 1;
}


static void gpx_graph_finalize (GpxGraph* obj) {
	GpxGraph * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GPX_TYPE_GRAPH, GpxGraph);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->track);
	_g_object_unref0 (self->priv->view);
}


GType gpx_graph_get_type (void) {
	static volatile gsize gpx_graph_type_id__volatile = 0;
	if (g_once_init_enter (&gpx_graph_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { gpx_value_graph_init, gpx_value_graph_free_value, gpx_value_graph_copy_value, gpx_value_graph_peek_pointer, "p", gpx_value_graph_collect_value, "p", gpx_value_graph_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (GpxGraphClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gpx_graph_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GpxGraph), 0, (GInstanceInitFunc) gpx_graph_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType gpx_graph_type_id;
		gpx_graph_type_id = g_type_register_fundamental (g_type_fundamental_next (), "GpxGraph", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&gpx_graph_type_id__volatile, gpx_graph_type_id);
	}
	return gpx_graph_type_id__volatile;
}


gpointer gpx_graph_ref (gpointer instance) {
	GpxGraph* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void gpx_graph_unref (gpointer instance) {
	GpxGraph* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		GPX_GRAPH_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



