/* gpx-settings.c generated by valac 0.28.1, the Vala compiler
 * generated from gpx-settings.vala, do not modify */

/* Gpx Viewer
 * Copyright (C) 2009-2015 Qball Cow <qball@sarine.nl>
 * Project homepage: http://blog.sarine.nl/

 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#include <glib.h>
#include <glib-object.h>
#include "gpx.h"
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <float.h>
#include <math.h>

#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define GPX_VIEWER_SETTINGS_TYPE___ENUM (gpx_viewer_settings___enum_get_type ())
#define _g_key_file_free0(var) ((var == NULL) ? NULL : (var = (g_key_file_free (var), NULL)))
#define _g_param_spec_unref0(var) ((var == NULL) ? NULL : (var = (g_param_spec_unref (var), NULL)))

struct _GpxViewerSettingsPrivate {
	GKeyFile* keyfile;
};

typedef enum  {
	GPX_VIEWER_SETTINGS___ENUM_FOO
} GpxViewerSettings__enum;


static gpointer gpx_viewer_settings_parent_class = NULL;
static gchar* gpx_viewer_settings_LOG_DOMAIN;
static gchar* gpx_viewer_settings_LOG_DOMAIN = NULL;
GType gpx_viewer_settings_enum_type = 0UL;

#define GPX_VIEWER_SETTINGS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GPX_VIEWER_TYPE_SETTINGS, GpxViewerSettingsPrivate))
enum  {
	GPX_VIEWER_SETTINGS_DUMMY_PROPERTY
};
static GType gpx_viewer_settings___enum_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static void gpx_viewer_settings_object_value_changed (GObject* object, GParamSpec* sp, GpxViewerSettings* pref);
static void gpx_viewer_settings_finalize (GObject* obj);


static GType gpx_viewer_settings___enum_get_type (void) {
	static volatile gsize gpx_viewer_settings___enum_type_id__volatile = 0;
	if (g_once_init_enter (&gpx_viewer_settings___enum_type_id__volatile)) {
		static const GEnumValue values[] = {{GPX_VIEWER_SETTINGS___ENUM_FOO, "GPX_VIEWER_SETTINGS___ENUM_FOO", "foo"}, {0, NULL, NULL}};
		GType gpx_viewer_settings___enum_type_id;
		gpx_viewer_settings___enum_type_id = g_enum_register_static ("GpxViewerSettings__enum", values);
		g_once_init_leave (&gpx_viewer_settings___enum_type_id__volatile, gpx_viewer_settings___enum_type_id);
	}
	return gpx_viewer_settings___enum_type_id__volatile;
}


GpxViewerSettings* gpx_viewer_settings_construct (GType object_type) {
	GpxViewerSettings * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* path = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
	self = (GpxViewerSettings*) g_object_new (object_type, NULL);
	_tmp0_ = gpx_viewer_settings_LOG_DOMAIN;
	g_log (_tmp0_, G_LOG_LEVEL_DEBUG, "gpx-settings.vala:45: Creating preferences");
	_tmp1_ = g_get_user_config_dir ();
	_tmp2_ = g_build_filename (_tmp1_, "gpx-viewer", "config.ini", NULL);
	path = _tmp2_;
	_tmp3_ = gpx_viewer_settings_LOG_DOMAIN;
	g_log (_tmp3_, G_LOG_LEVEL_DEBUG, "gpx-settings.vala:54: Loading from: %s", path);
	{
		GKeyFile* _tmp4_ = NULL;
		_tmp4_ = self->priv->keyfile;
		g_key_file_load_from_file (_tmp4_, path, G_KEY_FILE_NONE, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch7_g_error;
		}
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = gpx_viewer_settings_LOG_DOMAIN;
		_tmp6_ = e;
		_tmp7_ = _tmp6_->message;
		g_log (_tmp5_, G_LOG_LEVEL_WARNING, "gpx-settings.vala:61: Failed to load config file: %s", _tmp7_);
		_g_error_free0 (e);
	}
	__finally7:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (path);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_g_free0 (path);
	return self;
}


GpxViewerSettings* gpx_viewer_settings_new (void) {
	return gpx_viewer_settings_construct (GPX_VIEWER_TYPE_SETTINGS);
}


static void gpx_viewer_settings_object_value_changed (GObject* object, GParamSpec* sp, GpxViewerSettings* pref) {
	GType t = 0UL;
	GObject* _tmp0_ = NULL;
	GType _tmp1_ = 0UL;
	GValue value = {0};
	GParamSpec* _tmp2_ = NULL;
	GType _tmp3_ = 0UL;
	GValue _tmp4_ = {0};
	GObject* _tmp5_ = NULL;
	GParamSpec* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	GParamSpec* _tmp8_ = NULL;
	GType _tmp9_ = 0UL;
	g_return_if_fail (object != NULL);
	g_return_if_fail (sp != NULL);
	g_return_if_fail (pref != NULL);
	_tmp0_ = object;
	_tmp1_ = G_TYPE_FROM_INSTANCE (_tmp0_);
	t = _tmp1_;
	_tmp2_ = sp;
	_tmp3_ = _tmp2_->value_type;
	g_value_init (&_tmp4_, _tmp3_);
	value = _tmp4_;
	_tmp5_ = object;
	_tmp6_ = sp;
	_tmp7_ = _tmp6_->name;
	g_object_get_property (_tmp5_, _tmp7_, &value);
	_tmp8_ = sp;
	_tmp9_ = _tmp8_->value_type;
	if (_tmp9_ == G_TYPE_INT) {
		GpxViewerSettings* _tmp10_ = NULL;
		GKeyFile* _tmp11_ = NULL;
		GType _tmp12_ = 0UL;
		const gchar* _tmp13_ = NULL;
		GParamSpec* _tmp14_ = NULL;
		const gchar* _tmp15_ = NULL;
		gint _tmp16_ = 0;
		_tmp10_ = pref;
		_tmp11_ = _tmp10_->priv->keyfile;
		_tmp12_ = t;
		_tmp13_ = g_type_name (_tmp12_);
		_tmp14_ = sp;
		_tmp15_ = _tmp14_->name;
		_tmp16_ = g_value_get_int (&value);
		g_key_file_set_integer (_tmp11_, _tmp13_, _tmp15_, _tmp16_);
	} else {
		GParamSpec* _tmp17_ = NULL;
		GType _tmp18_ = 0UL;
		GType _tmp19_ = 0UL;
		gboolean _tmp20_ = FALSE;
		_tmp17_ = sp;
		_tmp18_ = _tmp17_->value_type;
		_tmp19_ = gpx_viewer_settings_enum_type;
		_tmp20_ = g_type_is_a (_tmp18_, _tmp19_);
		if (_tmp20_) {
			GpxViewerSettings* _tmp21_ = NULL;
			GKeyFile* _tmp22_ = NULL;
			GType _tmp23_ = 0UL;
			const gchar* _tmp24_ = NULL;
			GParamSpec* _tmp25_ = NULL;
			const gchar* _tmp26_ = NULL;
			gint _tmp27_ = 0;
			_tmp21_ = pref;
			_tmp22_ = _tmp21_->priv->keyfile;
			_tmp23_ = t;
			_tmp24_ = g_type_name (_tmp23_);
			_tmp25_ = sp;
			_tmp26_ = _tmp25_->name;
			_tmp27_ = g_value_get_enum (&value);
			g_key_file_set_integer (_tmp22_, _tmp24_, _tmp26_, (gint) _tmp27_);
		} else {
			GParamSpec* _tmp28_ = NULL;
			GType _tmp29_ = 0UL;
			gboolean _tmp30_ = FALSE;
			_tmp28_ = sp;
			_tmp29_ = _tmp28_->value_type;
			_tmp30_ = g_type_is_a (_tmp29_, G_TYPE_BOOLEAN);
			if (_tmp30_) {
				GpxViewerSettings* _tmp31_ = NULL;
				GKeyFile* _tmp32_ = NULL;
				GType _tmp33_ = 0UL;
				const gchar* _tmp34_ = NULL;
				GParamSpec* _tmp35_ = NULL;
				const gchar* _tmp36_ = NULL;
				gboolean _tmp37_ = FALSE;
				_tmp31_ = pref;
				_tmp32_ = _tmp31_->priv->keyfile;
				_tmp33_ = t;
				_tmp34_ = g_type_name (_tmp33_);
				_tmp35_ = sp;
				_tmp36_ = _tmp35_->name;
				_tmp37_ = g_value_get_boolean (&value);
				g_key_file_set_boolean (_tmp32_, _tmp34_, _tmp36_, _tmp37_);
			} else {
				GParamSpec* _tmp38_ = NULL;
				GType _tmp39_ = 0UL;
				gboolean _tmp40_ = FALSE;
				_tmp38_ = sp;
				_tmp39_ = _tmp38_->value_type;
				_tmp40_ = g_type_is_a (_tmp39_, G_TYPE_STRING);
				if (_tmp40_) {
					GpxViewerSettings* _tmp41_ = NULL;
					GKeyFile* _tmp42_ = NULL;
					GType _tmp43_ = 0UL;
					const gchar* _tmp44_ = NULL;
					GParamSpec* _tmp45_ = NULL;
					const gchar* _tmp46_ = NULL;
					const gchar* _tmp47_ = NULL;
					_tmp41_ = pref;
					_tmp42_ = _tmp41_->priv->keyfile;
					_tmp43_ = t;
					_tmp44_ = g_type_name (_tmp43_);
					_tmp45_ = sp;
					_tmp46_ = _tmp45_->name;
					_tmp47_ = g_value_get_string (&value);
					g_key_file_set_string (_tmp42_, _tmp44_, _tmp46_, _tmp47_);
				}
			}
		}
	}
	G_IS_VALUE (&value) ? (g_value_unset (&value), NULL) : NULL;
}


/**
             * Atomatically save and restore (on calling this function)
             * A GLib.Object property.
             */
static gpointer _g_param_spec_ref0 (gpointer self) {
	return self ? g_param_spec_ref (self) : NULL;
}


void gpx_viewer_settings_add_object_property (GpxViewerSettings* self, GObject* wobject, const gchar* property) {
	GParamSpec* sp = NULL;
	GObject* _tmp0_ = NULL;
	GObjectClass* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GParamSpec* _tmp3_ = NULL;
	GParamSpec* _tmp4_ = NULL;
	GParamSpec* _tmp5_ = NULL;
	gboolean _tmp8_ = FALSE;
	GParamSpec* _tmp9_ = NULL;
	GType _tmp10_ = 0UL;
	GObject* _tmp58_ = NULL;
	const gchar* _tmp59_ = NULL;
	gchar* _tmp60_ = NULL;
	gchar* _tmp61_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (wobject != NULL);
	g_return_if_fail (property != NULL);
	_tmp0_ = wobject;
	_tmp1_ = G_OBJECT_GET_CLASS (_tmp0_);
	_tmp2_ = property;
	_tmp3_ = g_object_class_find_property (_tmp1_, _tmp2_);
	_tmp4_ = _g_param_spec_ref0 (_tmp3_);
	sp = _tmp4_;
	_tmp5_ = sp;
	if (_tmp5_ == NULL) {
		const gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		_tmp6_ = gpx_viewer_settings_LOG_DOMAIN;
		_tmp7_ = property;
		g_log (_tmp6_, G_LOG_LEVEL_WARNING, "gpx-settings.vala:120: object has not property: %s", _tmp7_);
		_g_param_spec_unref0 (sp);
		return;
	}
	_tmp9_ = sp;
	_tmp10_ = _tmp9_->value_type;
	if (_tmp10_ == G_TYPE_INT) {
		_tmp8_ = TRUE;
	} else {
		GParamSpec* _tmp11_ = NULL;
		GType _tmp12_ = 0UL;
		GType _tmp13_ = 0UL;
		gboolean _tmp14_ = FALSE;
		_tmp11_ = sp;
		_tmp12_ = _tmp11_->value_type;
		_tmp13_ = gpx_viewer_settings_enum_type;
		_tmp14_ = g_type_is_a (_tmp12_, _tmp13_);
		_tmp8_ = _tmp14_;
	}
	if (_tmp8_) {
		gint val = 0;
		{
			gint _tmp15_ = 0;
			GKeyFile* _tmp16_ = NULL;
			GObject* _tmp17_ = NULL;
			GType _tmp18_ = 0UL;
			const gchar* _tmp19_ = NULL;
			GParamSpec* _tmp20_ = NULL;
			const gchar* _tmp21_ = NULL;
			gint _tmp22_ = 0;
			GObject* _tmp23_ = NULL;
			GParamSpec* _tmp24_ = NULL;
			const gchar* _tmp25_ = NULL;
			gint _tmp26_ = 0;
			_tmp16_ = self->priv->keyfile;
			_tmp17_ = wobject;
			_tmp18_ = G_TYPE_FROM_INSTANCE (_tmp17_);
			_tmp19_ = g_type_name (_tmp18_);
			_tmp20_ = sp;
			_tmp21_ = _tmp20_->name;
			_tmp22_ = g_key_file_get_integer (_tmp16_, _tmp19_, _tmp21_, &_inner_error_);
			_tmp15_ = _tmp22_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch8_g_error;
			}
			val = (gint) _tmp15_;
			_tmp23_ = wobject;
			_tmp24_ = sp;
			_tmp25_ = _tmp24_->name;
			_tmp26_ = val;
			g_object_set (_tmp23_, _tmp25_, _tmp26_, NULL);
		}
		goto __finally8;
		__catch8_g_error:
		{
			GError* e = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_g_error_free0 (e);
		}
		__finally8:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_param_spec_unref0 (sp);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	} else {
		GParamSpec* _tmp27_ = NULL;
		GType _tmp28_ = 0UL;
		gboolean _tmp29_ = FALSE;
		_tmp27_ = sp;
		_tmp28_ = _tmp27_->value_type;
		_tmp29_ = g_type_is_a (_tmp28_, G_TYPE_BOOLEAN);
		if (_tmp29_) {
			gboolean val = FALSE;
			{
				gboolean _tmp30_ = FALSE;
				GKeyFile* _tmp31_ = NULL;
				GObject* _tmp32_ = NULL;
				GType _tmp33_ = 0UL;
				const gchar* _tmp34_ = NULL;
				GParamSpec* _tmp35_ = NULL;
				const gchar* _tmp36_ = NULL;
				gboolean _tmp37_ = FALSE;
				GObject* _tmp38_ = NULL;
				GParamSpec* _tmp39_ = NULL;
				const gchar* _tmp40_ = NULL;
				gboolean _tmp41_ = FALSE;
				_tmp31_ = self->priv->keyfile;
				_tmp32_ = wobject;
				_tmp33_ = G_TYPE_FROM_INSTANCE (_tmp32_);
				_tmp34_ = g_type_name (_tmp33_);
				_tmp35_ = sp;
				_tmp36_ = _tmp35_->name;
				_tmp37_ = g_key_file_get_boolean (_tmp31_, _tmp34_, _tmp36_, &_inner_error_);
				_tmp30_ = _tmp37_;
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					goto __catch9_g_error;
				}
				val = _tmp30_;
				_tmp38_ = wobject;
				_tmp39_ = sp;
				_tmp40_ = _tmp39_->name;
				_tmp41_ = val;
				g_object_set (_tmp38_, _tmp40_, _tmp41_, NULL);
			}
			goto __finally9;
			__catch9_g_error:
			{
				GError* e = NULL;
				e = _inner_error_;
				_inner_error_ = NULL;
				_g_error_free0 (e);
			}
			__finally9:
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_param_spec_unref0 (sp);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		} else {
			GParamSpec* _tmp42_ = NULL;
			GType _tmp43_ = 0UL;
			gboolean _tmp44_ = FALSE;
			_tmp42_ = sp;
			_tmp43_ = _tmp42_->value_type;
			_tmp44_ = g_type_is_a (_tmp43_, G_TYPE_STRING);
			if (_tmp44_) {
				gchar* val = NULL;
				{
					gchar* _tmp45_ = NULL;
					GKeyFile* _tmp46_ = NULL;
					GObject* _tmp47_ = NULL;
					GType _tmp48_ = 0UL;
					const gchar* _tmp49_ = NULL;
					GParamSpec* _tmp50_ = NULL;
					const gchar* _tmp51_ = NULL;
					gchar* _tmp52_ = NULL;
					gchar* _tmp53_ = NULL;
					GObject* _tmp54_ = NULL;
					GParamSpec* _tmp55_ = NULL;
					const gchar* _tmp56_ = NULL;
					const gchar* _tmp57_ = NULL;
					_tmp46_ = self->priv->keyfile;
					_tmp47_ = wobject;
					_tmp48_ = G_TYPE_FROM_INSTANCE (_tmp47_);
					_tmp49_ = g_type_name (_tmp48_);
					_tmp50_ = sp;
					_tmp51_ = _tmp50_->name;
					_tmp52_ = g_key_file_get_string (_tmp46_, _tmp49_, _tmp51_, &_inner_error_);
					_tmp45_ = _tmp52_;
					if (G_UNLIKELY (_inner_error_ != NULL)) {
						goto __catch10_g_error;
					}
					_tmp53_ = _tmp45_;
					_tmp45_ = NULL;
					_g_free0 (val);
					val = _tmp53_;
					_tmp54_ = wobject;
					_tmp55_ = sp;
					_tmp56_ = _tmp55_->name;
					_tmp57_ = val;
					g_object_set (_tmp54_, _tmp56_, _tmp57_, NULL);
					_g_free0 (_tmp45_);
				}
				goto __finally10;
				__catch10_g_error:
				{
					GError* e = NULL;
					e = _inner_error_;
					_inner_error_ = NULL;
					_g_error_free0 (e);
				}
				__finally10:
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_free0 (val);
					_g_param_spec_unref0 (sp);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_g_free0 (val);
			}
		}
	}
	_tmp58_ = wobject;
	_tmp59_ = property;
	_tmp60_ = g_strconcat ("notify::", _tmp59_, NULL);
	_tmp61_ = _tmp60_;
	g_signal_connect_object (_tmp58_, _tmp61_, (GCallback) gpx_viewer_settings_object_value_changed, (GObject*) self, G_CONNECT_AFTER);
	_g_free0 (_tmp61_);
	_g_param_spec_unref0 (sp);
}


/**
             * manual config system
             */
gint gpx_viewer_settings_get_integer (GpxViewerSettings* self, const gchar* class, const gchar* name, gint def) {
	gint result = 0;
	gint val = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (class != NULL, 0);
	g_return_val_if_fail (name != NULL, 0);
	{
		gint _tmp0_ = 0;
		GKeyFile* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		_tmp1_ = self->priv->keyfile;
		_tmp2_ = class;
		_tmp3_ = name;
		_tmp4_ = g_key_file_get_integer (_tmp1_, _tmp2_, _tmp3_, &_inner_error_);
		_tmp0_ = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch11_g_error;
		}
		val = _tmp0_;
	}
	goto __finally11;
	__catch11_g_error:
	{
		GError* e = NULL;
		gint _tmp5_ = 0;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = def;
		val = _tmp5_;
		_g_error_free0 (e);
	}
	__finally11:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = val;
	return result;
}


gchar* gpx_viewer_settings_get_string (GpxViewerSettings* self, const gchar* class, const gchar* name, const gchar* def) {
	gchar* result = NULL;
	gchar* val = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (class != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	{
		gchar* _tmp0_ = NULL;
		GKeyFile* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		_tmp1_ = self->priv->keyfile;
		_tmp2_ = class;
		_tmp3_ = name;
		_tmp4_ = g_key_file_get_string (_tmp1_, _tmp2_, _tmp3_, &_inner_error_);
		_tmp0_ = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch12_g_error;
		}
		_tmp5_ = _tmp0_;
		_tmp0_ = NULL;
		_g_free0 (val);
		val = _tmp5_;
		_g_free0 (_tmp0_);
	}
	goto __finally12;
	__catch12_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp6_ = def;
		_tmp7_ = g_strdup (_tmp6_);
		_g_free0 (val);
		val = _tmp7_;
		_g_error_free0 (e);
	}
	__finally12:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (val);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	result = val;
	return result;
}


void gpx_viewer_settings_set_integer (GpxViewerSettings* self, const gchar* class, const gchar* name, gint val) {
	GKeyFile* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (class != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = self->priv->keyfile;
	_tmp1_ = class;
	_tmp2_ = name;
	_tmp3_ = val;
	g_key_file_set_integer (_tmp0_, _tmp1_, _tmp2_, _tmp3_);
}


void gpx_viewer_settings_set_string (GpxViewerSettings* self, const gchar* class, const gchar* name, const gchar* val) {
	GKeyFile* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (class != NULL);
	g_return_if_fail (name != NULL);
	g_return_if_fail (val != NULL);
	_tmp0_ = self->priv->keyfile;
	_tmp1_ = class;
	_tmp2_ = name;
	_tmp3_ = val;
	g_key_file_set_string (_tmp0_, _tmp1_, _tmp2_, _tmp3_);
}


gdouble gpx_viewer_settings_get_double (GpxViewerSettings* self, const gchar* class, const gchar* name, gdouble def) {
	gdouble result = 0.0;
	gdouble val = 0.0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0.0);
	g_return_val_if_fail (class != NULL, 0.0);
	g_return_val_if_fail (name != NULL, 0.0);
	{
		gdouble _tmp0_ = 0.0;
		GKeyFile* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		gdouble _tmp4_ = 0.0;
		_tmp1_ = self->priv->keyfile;
		_tmp2_ = class;
		_tmp3_ = name;
		_tmp4_ = g_key_file_get_double (_tmp1_, _tmp2_, _tmp3_, &_inner_error_);
		_tmp0_ = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch13_g_error;
		}
		val = _tmp0_;
	}
	goto __finally13;
	__catch13_g_error:
	{
		GError* e = NULL;
		gdouble _tmp5_ = 0.0;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = def;
		val = _tmp5_;
		_g_error_free0 (e);
	}
	__finally13:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0.0;
	}
	result = val;
	return result;
}


gboolean gpx_viewer_settings_get_boolean (GpxViewerSettings* self, const gchar* class, const gchar* name, gboolean def) {
	gboolean result = FALSE;
	gboolean val = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (class != NULL, FALSE);
	g_return_val_if_fail (name != NULL, FALSE);
	{
		gboolean _tmp0_ = FALSE;
		GKeyFile* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		gboolean _tmp4_ = FALSE;
		_tmp1_ = self->priv->keyfile;
		_tmp2_ = class;
		_tmp3_ = name;
		_tmp4_ = g_key_file_get_boolean (_tmp1_, _tmp2_, _tmp3_, &_inner_error_);
		_tmp0_ = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch14_g_error;
		}
		val = _tmp0_;
	}
	goto __finally14;
	__catch14_g_error:
	{
		GError* e = NULL;
		gboolean _tmp5_ = FALSE;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = def;
		val = _tmp5_;
		_g_error_free0 (e);
	}
	__finally14:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	result = val;
	return result;
}


static void gpx_viewer_settings_class_init (GpxViewerSettingsClass * klass) {
	gchar* _tmp0_ = NULL;
	GType _tmp1_ = 0UL;
	gpx_viewer_settings_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GpxViewerSettingsPrivate));
	G_OBJECT_CLASS (klass)->finalize = gpx_viewer_settings_finalize;
	_tmp0_ = g_strdup ("Gpx.Viewer.Settings");
	gpx_viewer_settings_LOG_DOMAIN = _tmp0_;
	_tmp1_ = g_type_parent (GPX_VIEWER_SETTINGS_TYPE___ENUM);
	gpx_viewer_settings_enum_type = _tmp1_;
}


static void gpx_viewer_settings_instance_init (GpxViewerSettings * self) {
	GKeyFile* _tmp0_ = NULL;
	self->priv = GPX_VIEWER_SETTINGS_GET_PRIVATE (self);
	_tmp0_ = g_key_file_new ();
	self->priv->keyfile = _tmp0_;
}


static void gpx_viewer_settings_finalize (GObject* obj) {
	GpxViewerSettings * self;
	const gchar* _tmp0_ = NULL;
	gsize size = 0UL;
	gchar* ini_data = NULL;
	GKeyFile* _tmp1_ = NULL;
	gsize _tmp2_ = 0UL;
	gchar* _tmp3_ = NULL;
	gchar* path = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	GError * _inner_error_ = NULL;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GPX_VIEWER_TYPE_SETTINGS, GpxViewerSettings);
	_tmp0_ = gpx_viewer_settings_LOG_DOMAIN;
	g_log (_tmp0_, G_LOG_LEVEL_DEBUG, "gpx-settings.vala:69: Destroying preferences");
	_tmp1_ = self->priv->keyfile;
	_tmp3_ = g_key_file_to_data (_tmp1_, &_tmp2_, NULL);
	size = _tmp2_;
	ini_data = _tmp3_;
	_tmp4_ = g_get_user_config_dir ();
	_tmp5_ = g_build_filename (_tmp4_, "gpx-viewer", "config.ini", NULL);
	path = _tmp5_;
	_tmp6_ = gpx_viewer_settings_LOG_DOMAIN;
	_tmp7_ = path;
	g_log (_tmp6_, G_LOG_LEVEL_DEBUG, "gpx-settings.vala:81: Saving to: %s", _tmp7_);
	{
		const gchar* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		gsize _tmp10_ = 0UL;
		_tmp8_ = path;
		_tmp9_ = ini_data;
		_tmp10_ = size;
		g_file_set_contents (_tmp8_, _tmp9_, (gssize) _tmp10_, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch6_g_error;
		}
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp11_ = NULL;
		GError* _tmp12_ = NULL;
		const gchar* _tmp13_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp11_ = gpx_viewer_settings_LOG_DOMAIN;
		_tmp12_ = e;
		_tmp13_ = _tmp12_->message;
		g_log (_tmp11_, G_LOG_LEVEL_WARNING, "gpx-settings.vala:87: Failed to store config file: %s", _tmp13_);
		_g_error_free0 (e);
	}
	__finally6:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (path);
		_g_free0 (ini_data);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
	}
	_g_free0 (path);
	_g_free0 (ini_data);
	_g_key_file_free0 (self->priv->keyfile);
	G_OBJECT_CLASS (gpx_viewer_settings_parent_class)->finalize (obj);
}


GType gpx_viewer_settings_get_type (void) {
	static volatile gsize gpx_viewer_settings_type_id__volatile = 0;
	if (g_once_init_enter (&gpx_viewer_settings_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GpxViewerSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gpx_viewer_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GpxViewerSettings), 0, (GInstanceInitFunc) gpx_viewer_settings_instance_init, NULL };
		GType gpx_viewer_settings_type_id;
		gpx_viewer_settings_type_id = g_type_register_static (G_TYPE_OBJECT, "GpxViewerSettings", &g_define_type_info, 0);
		g_once_init_leave (&gpx_viewer_settings_type_id__volatile, gpx_viewer_settings_type_id);
	}
	return gpx_viewer_settings_type_id__volatile;
}



